processhelp.pm: drop tasklist before taskkill
taskkill has two ways of killing a task:

1. `-pid <pid>`
   If `<pid>` is missing it returns 128 and outputs:
   ```
   ERROR: The process "<pid>" not found.
   ```

2. `-fi "PID eq <pid>"`
   If `<pid>` is missing, it returns 0 and outputs:
   ```
   INFO: No tasks running with the specified criteria.
   ```

The curl runner script doesn't check the result of the call and
both stdout and stderr are redirected to NUL.