cm: add workaround for LibreSSL missing `ws2_32` symbols
This issue was never addressed in cmake so far. curl-for-win worked
thanks to the `--start-group` workaround used there.

The accurate solution is to either pass what's necessary multiple times,
or arrange the libs in an order that make it work by default, without
duplications.

Only binutils ld is affected. llvm's lld and other linkers are not known
to be so picky.

```
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(bss_sock.c.obj):bss_sock.c:(.text$sock_ctrl[sock_ctrl]+0x59): undefined reference to `__imp_shutdown'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(bss_sock.c.obj):bss_sock.c:(.text$sock_free[sock_free]+0x30): undefined reference to `__imp_shutdown'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_init[CRYPTO_gcm128_init]+0x65): undefined reference to `__imp_ntohl'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_init[CRYPTO_gcm128_init]+0x98): undefined reference to `__imp_ntohl'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_setiv[CRYPTO_gcm128_setiv]+0x1f1): undefined reference to `__imp_ntohl'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_setiv[CRYPTO_gcm128_setiv]+0x228): undefined reference to `__imp_ntohl'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_setiv[CRYPTO_gcm128_setiv]+0x24f): undefined reference to `__imp_ntohl'
x86_64-w64-mingw32-ld: libressl/lib/libcrypto.a(gcm128.c.obj):gcm128.c:(.text$CRYPTO_gcm128_encrypt[CRYPTO_gcm128_encrypt]+0x98): more undefined references to `__imp_ntohl' follow
```