try silencing warning 1
dl-mingw, CM 4.8.1-x86_64 schannel (mingw-w64 3.0):
```
D:/a/curl/curl/tests/libtest/lib517.c: In function 'test_lib517':
D:/a/curl/curl/tests/libtest/lib517.c:147:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     {"Sun, 06 Nov 2044 08:49:37 GMT", (time_t) 2362034977 },
     ^
[normally commented:]
D:/a/curl/curl/tests/libtest/lib517.c:150:5: error: this decimal constant is unsigned only in ISO C90 [-Werror]
     {"Sun, 06 Nov 1900 08:49:37 GMT", -2182259423 },  /* causes warning on MSVC */
     ^
```
https://github.com/curl/curl/actions/runs/16540378828/job/46780712313?pr=18010#step:12:32

https://stackoverflow.com/questions/9941261/warning-this-decimal-constant-is-unsigned-only-in-iso-c90
https://gcc.gnu.org/legacy-ml/gcc-bugs/2003-04/msg00082.html