mbedtls: fix private member designations for v3.1.0
"As a last resort, you can access the field foo of a structure bar by writing bar.MBEDTLS_PRIVATE(foo). Note that you do so at your own risk, since such code is likely to break in a future minor version of Mbed TLS." - https://github.com/ARMmbed/mbedtls/blob/f2d1199edc5834df4297f247f213e614f7782d1d/docs/3.0-migration-guide.md

That future minor version is v3.1.0. I set the >= to == for the version checks because v3.1.0 is a release, and I am not sure when the private designation was reverted after v3.0.0. The change made to support v3.0.0 causes builds to break for v3.1.0 with the following errors:

[ 81%] Building C object deps/curl/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o
In file included from /c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/net_sockets.h:40,
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c: In function 'mbed_connect_step2':
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/private_access.h:27:33: error: 'mbedtls_x509_crt' has no member named 'private_raw'; did you mean 'private_sig'?
   27 | #define MBEDTLS_PRIVATE(member) private_##member
      |                                 ^~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c:703:32: note: in expansion of macro 'MBEDTLS_PRIVATE'
  703 |     if(!peercert || !peercert->MBEDTLS_PRIVATE(raw).MBEDTLS_PRIVATE(p) ||
      |                                ^~~~~~~~~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/private_access.h:27:33: error: 'mbedtls_x509_crt' has no member named 'private_raw'; did you mean 'private_sig'?
   27 | #define MBEDTLS_PRIVATE(member) private_##member
      |                                 ^~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c:704:19: note: in expansion of macro 'MBEDTLS_P      |                   ^~~~~~~~~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/private_access.h:27:33: error: 'mb   27 | #define MBEDTLS_PRIVATE(member) private_##member
      |                                 ^~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c:731:35: note: in expansion of macro 'MBEDTLS_PRIVATE'
  731 |                         peercert->MBEDTLS_PRIVATE(raw).MBEDTLS_PRIVATE(p),
      |                                   ^~~~~~~~~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/private_access.h:27:33: error: 'mbedtls_x509_crt' has no member named 'private_raw'; did you mean 'private_sig'?
   27 | #define MBEDTLS_PRIVATE(member) private_##member
      |                                 ^~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c:732:35: note: in expansion of macro 'MBEDTLS_PRIVATE'
  732 |                         peercert->MBEDTLS_PRIVATE(raw).MBEDTLS_PRIVATE(len))) {
      |                                   ^~~~~~~~~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/mbedtls-3.1.0/build/include/mbedtls/private_access.h:27:33: error: 'mbedtls_x509_crt' has no member named 'private_pk'; did you mean 'private_sig'?
   27 | #define MBEDTLS_PRIVATE(member) private_##member
      |                                 ^~~~~~~~
/c/Users/Valentin/Downloads/stateSpaceSolver/deps/curl/lib/vtls/mbedtls.c:742:44: note: in expansion of macro 'MBEDTLS_PRIVATE'
  742 |     size = mbedtls_pk_write_pubkey_der(&p->MBEDTLS_PRIVATE(pk), pubkey,
      |                                            ^~~~~~~~~~~~~~~
make[2]: *** [deps/curl/lib/CMakeFiles/libcurl.dir/build.make:1994: deps/curl/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o] Error 1