drop dragon upgrade
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Updating Avalon repository catalogue...
Avalon repository is up to date.
All repositories are up to date.
Checking for upgrades (27 candidates): .......... done
Processing candidates (27 candidates): .......... done
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
Cannot solve problem using SAT solver, trying another plan
The following 27 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	lame: 3.100_5 [Avalon]
	liburcu: 0.15.0 [Avalon]

Installed packages to be UPGRADED:
	abseil: 20230125.3 -> 20250127.0 [Avalon]
	ca_root_nss: 3.93_2 -> 3.108 [Avalon]
	expat: 2.6.2 -> 2.7.0 [Avalon]
	gettext-runtime: 0.22.5 -> 0.23.1 [Avalon]
	indexinfo: 0.3.1 -> 0.3.1_1 [Avalon]
	isc-dhcp44-server: 4.4.3P1_1 -> 4.4.3P1_2 [Avalon]
	json-c: 0.17 -> 0.18 [Avalon]
	jsoncpp: 1.9.5 -> 1.9.6_1 [Avalon]
	libedit: 3.1.20240517,1 -> 3.1.20250104,1 [Avalon]
	libidn2: 2.3.7 -> 2.3.8 [Avalon]
	libnghttp2: 1.62.1 -> 1.65.0 [Avalon]
	libpsl: 0.21.5_1 -> 0.21.5_2 [Avalon]
	libssh2: 1.11.0_1,3 -> 1.11.1,3 [Avalon]
	libuv: 1.48.0 -> 1.50.0 [Avalon]
	libxml2: 2.11.8 -> 2.11.9_1 [Avalon]
	pcre2: 10.43 -> 10.45 [Avalon]
	protobuf: 24.4,1 -> 29.3_1,1 [Avalon]
	protobuf-c: 1.4.1_2 -> 1.5.1_1 [Avalon]
	schilybase: 2024.03.21 -> 2024.03.21_1 [Avalon]

Installed packages to be REINSTALLED:
	fstrm-0.6.1_1 [Avalon] (provided shared library changed)

Installed packages to be REMOVED:
	bash: 5.2.37
	bind-tools: 9.18.30
	cdrtools: 2024.03.21
	curl: 8.14.1
	sudo: 1.9.17p1

Number of packages to be removed: 5
Number of packages to be installed: 2
Number of packages to be upgraded: 19
Number of packages to be reinstalled: 1

The operation will free 22 MiB.
10 MiB to be downloaded.
[1/22] Fetching indexinfo-0.3.1_1.pkg: . done
[2/22] Fetching abseil-20250127.0.pkg: .......... done
[3/22] Fetching libnghttp2-1.65.0.pkg: ... done
[4/22] Fetching libxml2-2.11.9_1.pkg: .......... done
[5/22] Fetching libedit-3.1.20250104,1.pkg: ... done
[6/22] Fetching libidn2-2.3.8.pkg: ... done
[7/22] Fetching schilybase-2024.03.21_1.pkg: .......... done
[8/22] Fetching jsoncpp-1.9.6_1.pkg: ...... done
[9/22] Fetching fstrm-0.6.1_1.pkg: . done
[10/22] Fetching libuv-1.50.0.pkg: ... done
[11/22] Fetching protobuf-29.3_1,1.pkg: .......... done
[12/22] Fetching liburcu-0.15.0.pkg: .... done
[13/22] Fetching isc-dhcp44-server-4.4.3P1_2.pkg: .......... done
[14/22] Fetching pcre2-10.45.pkg: .......... done
[15/22] Fetching libssh2-1.11.1,3.pkg: ....... done
[16/22] Fetching libpsl-0.21.5_2.pkg: .. done
[17/22] Fetching protobuf-c-1.5.1_1.pkg: ... done
[18/22] Fetching json-c-0.18.pkg: .. done
[19/22] Fetching gettext-runtime-0.23.1.pkg: ..... done
[20/22] Fetching expat-2.7.0.pkg: .... done
[21/22] Fetching ca_root_nss-3.108.pkg: ...... done
[22/22] Fetching lame-3.100_5.pkg: ........ done
Checking integrity... done (0 conflicting)
[1/27] Deinstalling bash-5.2.37...
[1/27] Deleting files for bash-5.2.37: .......... done
[2/27] Deinstalling bind-tools-9.18.30...
[2/27] Deleting files for bind-tools-9.18.30: .......... done
[3/27] Upgrading ca_root_nss from 3.93_2 to 3.108...
[3/27] Extracting ca_root_nss-3.108: ....... done
[4/27] Deinstalling cdrtools-2024.03.21...
[4/27] Deleting files for cdrtools-2024.03.21: .......... done
[5/27] Deinstalling curl-8.14.1...
[5/27] Deleting files for curl-8.14.1: .......... done
[6/27] Upgrading expat from 2.6.2 to 2.7.0...
[6/27] Extracting expat-2.7.0: .......... done
[7/27] Reinstalling fstrm-0.6.1_1...
[7/27] Extracting fstrm-0.6.1_1: .......... done
[8/27] Upgrading isc-dhcp44-server from 4.4.3P1_1 to 4.4.3P1_2...
===> Creating groups
Using existing group 'dhcpd'
===> Creating users
Using existing user 'dhcpd'
[8/27] Extracting isc-dhcp44-server-4.4.3P1_2: .......... done
[9/27] Upgrading json-c from 0.17 to 0.18...
[9/27] Extracting json-c-0.18: .......... done
[10/27] Installing lame-3.100_5...
[10/27] Extracting lame-3.100_5: .......... done
[11/27] Upgrading libedit from 3.1.20240517,1 to 3.1.20250104,1...
[11/27] Extracting libedit-3.1.20250104,1: .......... done
[12/27] Upgrading libnghttp2 from 1.62.1 to 1.65.0...
[12/27] Extracting libnghttp2-1.65.0: .......... done
[13/27] Upgrading libpsl from 0.21.5_1 to 0.21.5_2...
[13/27] Extracting libpsl-0.21.5_2: .......... done
[14/27] Upgrading libidn2 from 2.3.7 to 2.3.8...
[14/27] Extracting libidn2-2.3.8: .......... done
[15/27] Upgrading libssh2 from 1.11.0_1,3 to 1.11.1,3...
[15/27] Extracting libssh2-1.11.1,3: .......... done
[16/27] Installing liburcu-0.15.0...
[16/27] Extracting liburcu-0.15.0: .......... done
[17/27] Upgrading libuv from 1.48.0 to 1.50.0...
[17/27] Extracting libuv-1.50.0: .......... done
[18/27] Upgrading libxml2 from 2.11.8 to 2.11.9_1...
[18/27] Extracting libxml2-2.11.9_1: .......... done
[19/27] Upgrading pcre2 from 10.43 to 10.45...
[19/27] Extracting pcre2-10.45: .......... done
[20/27] Upgrading protobuf-c from 1.4.1_2 to 1.5.1_1...
[20/27] Extracting protobuf-c-1.5.1_1: .......... done
[21/27] Upgrading protobuf from 24.4,1 to 29.3_1,1...
[21/27] Extracting protobuf-29.3_1,1: .......... done
[22/27] Upgrading abseil from 20230125.3 to 20250127.0...
[22/27] Extracting abseil-20250127.0: .......... done
[23/27] Upgrading jsoncpp from 1.9.5 to 1.9.6_1...
[23/27] Extracting jsoncpp-1.9.6_1: .......... done
[24/27] Upgrading schilybase from 2024.03.21 to 2024.03.21_1...
[24/27] Extracting schilybase-2024.03.21_1: .......... done
[25/27] Deinstalling sudo-1.9.17p1...
[25/27] Deleting files for sudo-1.9.17p1: .......... done
pkg: unlinkat(var/run/sudo): No such file or directory
[26/27] Upgrading gettext-runtime from 0.22.5 to 0.23.1...
[26/27] Extracting gettext-runtime-0.23.1: .......... done
[27/27] Upgrading indexinfo from 0.3.1 to 0.3.1_1...
[27/27] Extracting indexinfo-0.3.1_1: .... done
/bin/sh: sudo: not found
Error: Process completed with exit code 127.
```
https://github.com/curl/curl/actions/runs/28032613839/job/82977129421