try fix 2
```
scan-build: Using '/usr/lib/llvm-18/bin/clang' for static analysis
configure: error: unrecognized option: `-Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/gsasl/lib''
Try `../configure --help' for more information
scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2025-09-21-235437-4833-1' because it contains no reports.
scan-build: No bugs found.
Error: Process completed with exit code 1.
```
https://github.com/curl/curl/actions/runs/17900610492/job/50893093728?pr=18660