Revert "TEST `(void)!` cast 1"
This reverts commit 030130c2037b53de5983902aa8209eb3f43f0157.

home/runner/work/curl/curl/tests/server/util.c:329:5: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  329 |     write(STDERR_FILENO, msg, sizeof(msg) - 1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/tests/server/util.c:342:7: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  342 |       write(fd, msg, sizeof(msg) - 1);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/tests/server/util.c:347:7: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  347 |       write(STDERR_FILENO, msg, sizeof(msg) - 1);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/tests/server/util.c:348:7: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  348 |       write(STDERR_FILENO, serverlogfile, strlen(serverlogfile));
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/tests/server/util.c:349:7: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  349 |       write(STDERR_FILENO, "\n", 1);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Only in a couple of jobs, I wonder why only in those.

https://github.com/curl/curl/actions/runs/27548333990/job/81427544632?pr=22010
https://github.com/curl/curl/actions/runs/27548333990/job/81427553296?pr=22010

Only in these 5:
```
dist / AM in-tree & maketgz (pull_request)
Linux / AM awslc (pull_request)
Linux / AM curl_global_init_mem debug valgrind (pull_request)
Linux / CM openssl -O3 libssh valgrind 1 (pull_request)
Linux / CM openssl -O3 libssh valgrind 2 (pull_request)
````