exclude curl/curl.h
Due to:
```
/Users/runner/work/curl/curl/include/curl/mprintf.h:29:10: error: circular header file dependency detected while including 'curl.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]
   29 | #include "curl.h"  /* for CURL_EXTERN */
      |          ^
/Users/runner/work/curl/curl/include/curl/curl.h:3319:10: note: 'mprintf.h' included from here
 3319 | #include "mprintf.h"
      |          ^
/Users/runner/work/curl/curl/docs/examples/cacertinmem.c:35:10: note: 'curl.h' included from here
   35 | #include <curl/curl.h>
      |          ^
/Users/runner/work/curl/curl/include/curl/multi.h:51:10: error: circular header file dependency detected while including 'curl.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]
   51 | #include "curl.h"
      |          ^
/Users/runner/work/curl/curl/include/curl/curl.h:3314:10: note: 'multi.h' included from here
 3314 | #include "multi.h"
      |          ^
/Users/runner/work/curl/curl/docs/examples/cacertinmem.c:35:10: note: 'curl.h' included from here
   35 | #include <curl/curl.h>
      |          ^
/Users/runner/work/curl/curl/include/curl/urlapi.h:27:10: error: circular header file dependency detected while including 'curl.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]
   27 | #include "curl.h"
      |          ^
/Users/runner/work/curl/curl/include/curl/curl.h:3315:10: note: 'urlapi.h' included from here
 3315 | #include "urlapi.h"
      |          ^
/Users/runner/work/curl/curl/docs/examples/cacertinmem.c:35:10: note: 'curl.h' included from here
   35 | #include <curl/curl.h>
      |          ^
3 warnings generated.
3 warnings treated as errors
```
https://github.com/curl/curl/actions/runs/22225019638/job/64289405692?pr=20645