openssl: fix unused variable warnings in !verbose builds
```
lib/vtls/openssl.c:4055:46: error: unused parameter 'reason' [-Werror,-Wunused-parameter]
 4055 |                                          int reason)
      |                                              ^
lib/vtls/openssl.c:4279:19: error: variable 'status' set but not used [-Werror,-Wunused-but-set-variable]
 4279 |       const char *status = NULL;
      |                   ^
```
Ref: https://github.com/curl/curl/actions/runs/24641388439/job/72045859306?pr=21379

Cherry-picked from #21379