silence unused macro in parsedate.c
```
/Users/runner/work/curl/curl/lib/parsedate.c:103:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  103 | #define PARSEDATE_SOONER 2
      |         ^
1 warning generated.
```
https://github.com/curl/curl/actions/runs/13232157963/job/36930964574?pr=16279#step:11:111