build: fix libssh2 + schannel + `CURL_DISABLE_DIGEST_AUTH` + `CURL_DISABLE_AWS` builds
HMAC is required by `Curl_sha256it` which is required
by `vssh/libssh2.c`. Make sure to compile it.

Fixes:
```
[...]
In file included from ./curl/_x64-win-ucrt-cmake-llvm-bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:310:
./curl/lib/sha256.c:527:42: error: array has incomplete element type 'const struct HMAC_params'
  527 | const struct HMAC_params Curl_HMAC_SHA256[] = {
      |                                          ^
./curl/lib/curl_sha256.h:34:21: note: forward declaration of 'struct HMAC_params'
[...]
```

Fixes #12273
Closes #xxxxx