picky: backtrack
In Linux CM aws-lc job, HAVE_SNPRINTF fails due to (builtin-declaration-mismatch
is normally a warning)
```
    buildResult:
      variable: "HAVE_SNPRINTF"
      cached: true
      stdout: |
        Change Dir: '/home/runner/work/curl/curl/CMakeFiles/CMakeScratch/'

        Run Build Command(s): /usr/bin/ninja -v ...
        [1/2] /usr/bin/cc   -pedantic-errors -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wpragmas -Wstrict-aliasing=3 -Wdouble-promotion -Wformat=2 -Wtrampolines -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Wunused-const-variable -Walloc-zero -Wduplicated-branches -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Warith-conversion -Wenum-conversion -Werror -D_GNU_SOURCE -I/usr/include -I/usr/include -I/usr/include -DCHECK_FUNCTION_EXISTS=snprintf -o CMakeFiles/....dir/CheckFunctionExists.c.o -c /home/runner/work/curl/curl/CMakeFiles/CMakeScratch//CheckFunctionExists.c
        FAILED: CMakeFiles/....dir/CheckFunctionExists.c.o
        /usr/bin/cc   -pedantic-errors -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wpragmas -Wstrict-aliasing=3 -Wdouble-promotion -Wformat=2 -Wtrampolines -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Wunused-const-variable -Walloc-zero -Wduplicated-branches -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Warith-conversion -Wenum-conversion -Werror -D_GNU_SOURCE -I/usr/include -I/usr/include -I/usr/include -DCHECK_FUNCTION_EXISTS=snprintf -o CMakeFiles/....dir/CheckFunctionExists.c.o -c /home/runner/work/curl/curl/CMakeFiles/CMakeScratch//CheckFunctionExists.c
        <command-line>: error: conflicting types for built-in function ‘snprintf’; expected ‘int(char *, long unsigned int,  const char *, ...)’ [-Werror=builtin-declaration-mismatch]
        /home/runner/work/curl/curl/CMakeFiles/CMakeScratch//CheckFunctionExists.c:7:3: note: in expansion of macro ‘CHECK_FUNCTION_EXISTS’
            7 |   CHECK_FUNCTION_EXISTS(void);
              |   ^~~~~~~~~~~~~~~~~~~~~
        /home/runner/work/curl/curl/CMakeFiles/CMakeScratch//CheckFunctionExists.c:1:1: note: ‘snprintf’ is declared in header ‘<stdio.h>’
          +++ |+#include <stdio.h>
            1 | #ifdef CHECK_FUNCTION_EXISTS
```

Maybe should use check_symbol_exists()?