Revert "idn: fix warning in certain mingw-w64 env"
This reverts commit 6c8068dfdecbef0390eac1c77e06b8db4e0fca5c.

Not good, this time with CMake, missing the original declarations:

They are guarded with in winnls.h:
```
  #if WINVER >= 0x0600
```

```
/home/runner/work/curl/curl/lib/idn.c: In function ‘win32_idn_to_ascii’:
/home/runner/work/curl/curl/lib/idn.c:174:17: error: implicit declaration of function ‘IdnToAscii’; did you mean ‘ToAscii’? [-Wimplicit-function-declaration]
  174 |     int chars = IdnToAscii(0, in_w, (int)(wcslen(in_w) + 1), punycode,
      |                 ^~~~~~~~~~
      |                 ToAscii
/home/runner/work/curl/curl/lib/idn.c:174:17: error: nested extern declaration of ‘IdnToAscii’ [-Werror=nested-externs]
/home/runner/work/curl/curl/lib/idn.c: In function ‘win32_ascii_to_idn’:
/home/runner/work/curl/curl/lib/idn.c:204:17: error: implicit declaration of function ‘IdnToUnicode’; did you mean ‘ToUnicode’? [-Wimplicit-function-declaration]
  204 |     int chars = IdnToUnicode(0, in_w, (int)(wcslen(in_w) + 1), idn,
      |                 ^~~~~~~~~~~~
      |                 ToUnicode
/home/runner/work/curl/curl/lib/idn.c:204:17: error: nested extern declaration of ‘IdnToUnicode’ [-Werror=nested-externs]
```
Ref: https://github.com/curl/curl/actions/runs/10545946413/job/29216819270?pr=13947#step:11:76