add missing CURL_STATICLIB for Windows
```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/test-consumer-static-fetch.dir/test.c.obj:test.c:(.text+0x11f): undefined reference to `__imp_curl_version'
collect2.exe: error: ld returned 1 exit status
```
https://github.com/curl/curl/actions/runs/16784516811/job/47531518325?pr=18208#step:5:175