initialize nghttpx when testing a non-H3 build
Did not help, failure replace by:
```
FAILED ../../tests/http/test_07_upload.py::TestUpload::test_07_70_put_earlydata[h2-limited-body] -
  AssertionError: download /Users/runner/work/curl/curl/tests/http/gen/gw1/hx-upload/download_0.data missing
```