requires mingw-w64 9.0 or newer
https://github.com/curl/curl/actions/runs/13401270664/job/37432463680?pr=16385
```
-- Found MINGW64_VERSION=6.0
[...]
In file included from D:/a/curl/curl/bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_5_c.c:10:0:
D:/a/curl/curl/lib/vtls/schannel.c: In function 'schannel_connect_step1':
D:/a/curl/curl/lib/vtls/schannel.c:1007:7: error: 'SecApplicationProtocolNegotiationExt_ALPN' undeclared (first use in this function)
       SecApplicationProtocolNegotiationExt_ALPN;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/vtls/schannel.c:1007:7: note: each undeclared identifier is reported only once for each function it appears in
D:/a/curl/curl/lib/vtls/schannel.c:1029:27: error: 'SECBUFFER_APPLICATION_PROTOCOLS' undeclared (first use in this function); did you mean 'SECBUFFER_NEGOTIATION_INFO'?
     InitSecBuffer(&inbuf, SECBUFFER_APPLICATION_PROTOCOLS, alpn_buffer, cur);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           SECBUFFER_NEGOTIATION_INFO
D:/a/curl/curl/lib/vtls/schannel.c: In function 'schannel_connect_step3':
D:/a/curl/curl/lib/vtls/schannel.c:1534:3: error: unknown type name 'SecPkgContext_ApplicationProtocol'; did you mean 'SecPkgContext_NegotiationInfoW'?
[ 33%] Generating CURLOPT_XOAUTH2_BEARER.3, CURLSHOPT_LOCKFUNC.3, CURLSHOPT_SHARE.3, CURLSHOPT_UNLOCKFUNC.3, CURLSHOPT_UNSHARE.3, CURLSHOPT_USERDATA.3
   SecPkgContext_ApplicationProtocol alpn_result;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   SecPkgContext_NegotiationInfoW
D:/a/curl/curl/lib/vtls/schannel.c:1566:40: error: 'SECPKG_ATTR_APPLICATION_PROTOCOL' undeclared (first use in this function); did you mean 'SECPKG_ATTR_SUPPORTED_PROTOCOLS'?
                                        SECPKG_ATTR_APPLICATION_PROTOCOL,
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                        SECPKG_ATTR_SUPPORTED_PROTOCOLS
D:/a/curl/curl/lib/vtls/schannel.c:1574:19: error: request for member 'ProtoNegoStatus' in something not a structure or union
     if(alpn_result.ProtoNegoStatus ==
                   ^
D:/a/curl/curl/lib/vtls/schannel.c:1575:8: error: 'SecApplicationProtocolNegotiationStatus_Success' undeclared (first use in this function)
        SecApplicationProtocolNegotiationStatus_Success) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/vtls/schannel.c:1578:62: error: request for member 'ProtocolId' in something not a structure or union
       Curl_alpn_set_negotiated(cf, data, connssl, alpn_result.ProtocolId,
                                                              ^
D:/a/curl/curl/lib/vtls/schannel.c:1579:43: error: request for member 'ProtocolIdSize' in something not a structure or union
                                alpn_result.ProtocolIdSize);
                                           ^
```