cf-socket.c: add missing intermediate const
```
../../lib/cf-socket.c: In function 'bindlocal':
../../lib/cf-socket.c:734:32: error: to be safe all intermediate pointers in cast from 'char **' to 'const char **' must be 'const' qualified [-Werror=cast-qual]
  734 |             if(Curl_str_number((const char **)&scope_ptr, &scope_id, UINT_MAX))
      |                                ^
```