Revert "make the openssl job use msys2 libs only try 1"
This reverts commit 376a9dbc651b6f3274a2228b3b632094a9e8a92e.

Still doesn't work because zlib's zconf.h is target-dependent
and MSYS2's copy is incompatible with MSVC.

zlib being the dependency of everything, means it's a blocker
for combining / reusing packages between compiler. What an
unnecessary issue... Public headers should never be target
dependent.

```
C:\msys64\ucrt64\include\zconf.h(484,14): error C1083: Cannot open include file: 'unistd.h': No such file or directory
```

zconf.h:
```
 #if 1    /* was set to #if 1 by ./configure */
 #  define Z_HAVE_UNISTD_H
 #endif

 #if 1    /* was set to #if 1 by ./configure */
 #  define Z_HAVE_STDARG_H
 #endif
```