amiga: fix building libtests due to missing `RLIMIT_NOFILE`
By dropping -lunix from custom LIBS list.

Including `-lunix` causes setrlimit() and getrlimit() to be
auto-detected. This in turn makes lib518 and lib537 use them,
but they fail with:

```
In file included from libtest_bundle.c:2925:0:
../../../tests/libtest/lib518.c: In function 'test_rlimit_lib518':
../../../tests/libtest/lib518.c:134:16: error: 'RLIMIT_NOFILE' undeclared (first use in this function)
   if(getrlimit(RLIMIT_NOFILE, &rl) != 0) {
                ^~~~~~~~~~~~~
../../../tests/libtest/lib518.c:134:16: note: each undeclared identifier is reported only once for each function it appears in
In file included from libtest_bundle.c:4787:0:
../../../tests/libtest/lib537.c: In function 'test_rlimit_lib537':
../../../tests/libtest/lib537.c:132:16: error: 'RLIMIT_NOFILE' undeclared (first use in this function)
   if(getrlimit(RLIMIT_NOFILE, &rl) != 0) {
                ^~~~~~~~~~~~~
```

`RLIMIT_NOFILE` is provided by `sys/resource.h` which is correctly
detected and used, but the AmigeOS toolchain offers two different
versions of this file:

/opt/appveyor/build-agent/opt/amiga/m68k-amigaos/clib2/include/sys/resource.h
/opt/appveyor/build-agent/opt/amiga/m68k-amigaos/sys-include/sys/resource.h

The latter offers `RLIMIT_NOFILE` but not the former. The former just
references it:
```c
```

I don't know how to fix the header path confusion, so fix this by
making the build not detect and not use these functions.

verbose gcc output looked like this if anyone is wondering:
```
GNU C11 (GCC) version 6.5.0b 220613185627 (m68k-amigaos)
	compiled by GNU C version 9.4.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version none
warning: GMP header version 6.1.2 differs from library version 6.3.0.
warning: MPFR header version 4.0.1 differs from library version 4.2.1.
warning: MPC header version 1.1.0 differs from library version 1.3.1.
GGC heuristics: --param ggc-min-expand=93 --param ggc-min-heapsize=118982
ignoring nonexistent directory "/opt/appveyor/build-agent/opt/amiga/libexec/gcc/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/include"
ignoring nonexistent directory "/opt/appveyor/build-agent/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/ndk-include"
ignoring nonexistent directory "/opt/appveyor/build-agent/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/sys-include"
ignoring nonexistent directory "/opt/appveyor/build-agent/opt/amiga/libexec/gcc/m68k-amigaos/m68k-amigaos/include"
 ../../../include
 ../../lib
 ../../../lib
 ../../../tests/libtest
 /opt/appveyor/build-agent/opt/amiga/include
 /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/clib2/include
 /opt/appveyor/AmiSSL/Developer/include
 /opt/appveyor/build-agent/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/include
 /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/ndk-include
 /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/sys-include
 /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/include
End of search list.
GNU C11 (GCC) version 6.5.0b 220613185627 (m68k-amigaos)
	compiled by GNU C version 9.4.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version none
warning: GMP header version 6.1.2 differs from library version 6.3.0.
warning: MPFR header version 4.0.1 differs from library version 4.2.1.
warning: MPC header version 1.1.0 differs from library version 1.3.1.
GGC heuristics: --param ggc-min-expand=93 --param ggc-min-heapsize=118982
Compiler executable checksum: 53a646fb4b4253540c771c204d85ff26
```