try finalize 1
can't redefine because:
```
/home/runner/work/curl/curl/lib/sha256.c:63:22: error: call to undeclared function 'EVP_MD_CTX_create'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   63 |   ctx->openssl_ctx = EVP_MD_CTX_create();
      |                      ^
/home/runner/work/curl/curl/lib/sha256.c:63:22: note: did you mean 'EVP_MD_CTX_free'?
/usr/include/openssl/evp.h:700:6: note: 'EVP_MD_CTX_free' declared here
  700 | void EVP_MD_CTX_free(EVP_MD_CTX *ctx);
      |      ^
In file included from /home/runner/work/curl/curl/bld/lib/CMakeFiles/libcurl_static.dir/Unity/unity_0_c.c:310:
/home/runner/work/curl/curl/lib/sha256.c:63:20: error: incompatible integer to pointer conversion assigning to 'EVP_MD_CTX *' (aka 'struct evp_md_ctx_st *') from 'int' [-Wint-conversion]
   63 |   ctx->openssl_ctx = EVP_MD_CTX_create();
      |                    ^ ~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/sha256.c:68:5: error: call to undeclared function 'EVP_MD_CTX_destroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   68 |     EVP_MD_CTX_destroy(ctx->openssl_ctx);
      |     ^
/home/runner/work/curl/curl/lib/sha256.c:86:3: error: call to undeclared function 'EVP_MD_CTX_destroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   86 |   EVP_MD_CTX_destroy(ctx->openssl_ctx);
      |   ^
In file included from /home/runner/work/curl/curl/bld/lib/CMakeFiles/libcurl_static.dir/Unity/unity_0_c.c:439:
/home/runner/work/curl/curl/lib/vtls/openssl.c:5468:11: error: call to undeclared function 'EVP_MD_CTX_create'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 5468 |   mdctx = EVP_MD_CTX_create();
      |           ^
/home/runner/work/curl/curl/lib/vtls/openssl.c:5468:9: error: incompatible integer to pointer conversion assigning to 'EVP_MD_CTX *' (aka 'struct evp_md_ctx_st *') from 'int' [-Wint-conversion]
 5468 |   mdctx = EVP_MD_CTX_create();
      |         ^ ~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/openssl.c:5472:5: error: call to undeclared function 'EVP_MD_CTX_destroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 5472 |     EVP_MD_CTX_destroy(mdctx);
      |     ^
/home/runner/work/curl/curl/lib/vtls/openssl.c:5477:3: error: call to undeclared function 'EVP_MD_CTX_destroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 5477 |   EVP_MD_CTX_destroy(mdctx);
      |   ^
8 errors generated.
```
https://github.com/curl/curl/actions/runs/23453717544/job/68237366259?pr=21077