cmake: force-disable `getaddrinfo` for AmigaOS
autotools doesn't detect it (because it's a macro), but cmake does.
It then causes the build to fail:

```
In file included from lib/hostip.h:29:0,
                 from lib/urldata.h:160,
                 from lib/altsvc.c:32,
lib/curl_addrinfo.h:70:34: warning: 'struct addrinfo' declared inside parameter list will not be visible outside of this definition or declaration
                     const struct addrinfo *hints,
                                  ^~~~~~~~
lib/curl_addrinfo.c:106:1: error: conflicting types for 'Curl_getaddrinfo_ex'
 Curl_getaddrinfo_ex(const char *nodename,
 ^~~~~~~~~~~~~~~~~~~
In file included from lib/hostip.h:29:0,
                 from lib/urldata.h:160,
                 from lib/altsvc.c:32,
lib/curl_addrinfo.h:68:1: note: previous declaration of 'Curl_getaddrinfo_ex' was here
 Curl_getaddrinfo_ex(const char *nodename,
 ^~~~~~~~~~~~~~~~~~~
lib/curl_addrinfo.c: In function 'Curl_getaddrinfo_ex':
lib/curl_addrinfo.c:121:11: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
   error = getaddrinfo(nodename, servname, hints, &aihead);
           ^~~~~~~~~~~
lib/curl_addrinfo.c:121:11: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
lib/curl_addrinfo.c:127:39: error: dereferencing pointer to incomplete type 'const struct addrinfo'
   for(ai = aihead; ai != NULL; ai = ai->ai_next) {
                                       ^~
lib/curl_addrinfo.c:150:15: error: 'EAI_MEMORY' undeclared (first use in this function)
       error = EAI_MEMORY;
               ^~~~~~~~~~
lib/curl_addrinfo.c:150:15: note: each undeclared identifier is reported only once for each function it appears in
lib/curl_addrinfo.c:200:13: error: 'EAI_NODATA' undeclared (first use in this function)
     error = EAI_NODATA;
             ^~~~~~~~~~
lib/hostip4.c: In function 'Curl_ipv4_resolve_r':
lib/hostip4.c:135:19: error: storage size of 'hints' isn't known
   struct addrinfo hints;
                   ^~~~~
lib/hostip4.c:135:19: warning: unused variable 'hints' [-Wunused-variable]
```

Sync it manually with autotools to avoid the fallouts.