fixed potential unused variable
lib/vtls/vtls.c:1634:51: error: unused parameter 'conn' [-Werror,-Wunused-parameter]
 1634 |                               struct connectdata *conn)
      |                                                   ^