disable -Wunused-macro (not ready for permanent use)
The `CM clang OpenSSL AppleIDN clang-tidy +examples` job is finding
further cases, and due to clang-tidy it flags them as errors and
fails on the first one. I stopped cleaning up at `openssl.c` when
bumping into these non-trivial cases to silence:

```
/Users/runner/work/curl/curl/lib/vtls/openssl.c:110:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  110 | #define OPENSSL_HAS_PROVIDERS
      |         ^
/Users/runner/work/curl/curl/lib/vtls/openssl.c:141:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  141 | #define HAVE_ERR_REMOVE_THREAD_STATE
      |         ^
```
https://github.com/curl/curl/actions/runs/13232573832/job/36932009939?pr=16279#step:11:195