finalize AppVeyor unity tests
A unity fallout happens with openssl + schannel builds.
disabling openssl fixes it:
```
C:/projects/curl/lib/vtls/schannel.c: In function 'schannel_connect_step1':
C:/projects/curl/lib/vtls/schannel.c:1217:7: error: 'SecApplicationProtocolNegotiationExt_ALPN' undeclared (first use in this function)
       SecApplicationProtocolNegotiationExt_ALPN;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/projects/curl/lib/vtls/schannel.c:1217:7: note: each undeclared identifier is reported only once for each function it appears in
C:/projects/curl/lib/vtls/schannel.c:1240:27: error: 'SECBUFFER_APPLICATION_PROTOCOLS' undeclared (first use in this function); did you mean 'SECBUFFER_NEGOTIATION_INFO'?
     InitSecBuffer(&inbuf, SECBUFFER_APPLICATION_PROTOCOLS, alpn_buffer, cur);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           SECBUFFER_NEGOTIATION_INFO
C:/projects/curl/lib/vtls/schannel.c: In function 'schannel_connect_step3':
C:/projects/curl/lib/vtls/schannel.c:1698:3: error: unknown type name 'SecPkgContext_ApplicationProtocol'; did you mean 'SecPkgContext_ConnectionInfo'?
   SecPkgContext_ApplicationProtocol alpn_result;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   SecPkgContext_ConnectionInfo
C:/projects/curl/lib/vtls/schannel.c:1730:40: error: 'SECPKG_ATTR_APPLICATION_PROTOCOL' undeclared (first use in this function); did you mean 'SECPKG_ATTR_SUPPORTED_PROTOCOLS'?
                                        SECPKG_ATTR_APPLICATION_PROTOCOL,
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                        SECPKG_ATTR_SUPPORTED_PROTOCOLS
C:/projects/curl/lib/vtls/schannel.c:1738:19: error: request for member 'ProtoNegoStatus' in something not a structure or union
     if(alpn_result.ProtoNegoStatus ==
                   ^
C:/projects/curl/lib/vtls/schannel.c:1739:8: error: 'SecApplicationProtocolNegotiationStatus_Success' undeclared (first use in this function)
        SecApplicationProtocolNegotiationStatus_Success) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/projects/curl/lib/vtls/schannel.c:1742:53: error: request for member 'ProtocolId' in something not a structure or union
       Curl_alpn_set_negotiated(cf, data, alpn_result.ProtocolId,
                                                     ^
C:/projects/curl/lib/vtls/schannel.c:1743:43: error: request for member 'ProtocolIdSize' in something not a structure or union
                                alpn_result.ProtocolIdSize);
                                           ^
make[2]: *** [lib/CMakeFiles/libcurl.dir/build.make:64: lib/CMakeFiles/libcurl.dir/Unity/unity_0.c.obj] Error 1
make[2]: Target 'lib/CMakeFiles/libcurl.dir/build' not remade because of errors
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/47230972/job/51wfesgnfuauwl8q#L250

Bad attempts:
https://ci.appveyor.com/project/curlorg/curl/builds/47230369
https://ci.appveyor.com/project/curlorg/curl/builds/47230369/job/cpr9b67a2al293qj
  `tests\unit\unit3200.exe` -> hung
https://ci.appveyor.com/project/curlorg/curl/builds/47230369/job/6usv7td7sfb6f4bm
  `could not get curl version! at C:/projects/curl/tests/runtests.pl line 2360.`

Also:
- appveyor.yml: add 'dll' to libcurl artifact name