test/server: fix shadowing variable 'path'
Rename a global variable in server code to avoid colliding with its name
used elsewhere in libcurl. This isn't causing an issue at this time, but
makes the code sensitive to compile order, and may cause `-Wshadow`
warnings if the global declaration precedes libcurl code:
```
lib/curl_multibyte.c:317:34: error: declaration of 'path' shadows a global declaration [-Werror=shadow]
  317 | int curlx_win32_stat(const char *path, struct_stat *buffer)
      |                      ~~~~~~~~~~~~^~~~
In file included from tests/server/resolve.c:47,
                 from bld/tests/server/server_bundle.c:7,
                 from bld/tests/server/CMakeFiles/servers.dir/Unity/unity_0_c.c:4:
tests/server/util.h:64:20: note: shadowed declaration is here
   64 | extern const char *path;  /* where to find the 'data' dir */
      |                    ^~~~
```

Affecting these CI jobs:
```
AppVeyor / CMake, VS2022, Release, x64, Schannel, Shared, Unicode, DEBUGBUILD, no-CURLDEBUG, Build-tests
Windows / linux-mingw, CM gcc
Windows / mingw, CM i686 schannel R
Windows / mingw, CM ucrt-x86_64 schannel uwp
Windows / msvc, CM x64-windows boringssl
```

https://github.com/curl/curl/actions/runs/13845123447/job/38741731971?pr=15000
https://ci.appveyor.com/project/curlorg/curl/builds/51693340