url: fix unused variable in UWP builds
UWP builds don't support iphlpapi's if_nametoindex().

```
D:/a/curl/curl/lib/url.c: In function 'zonefrom_url':
D:/a/curl/curl/lib/url.c:1777:55: error: unused parameter 'data' [-Werror=unused-parameter]
 1777 | static void zonefrom_url(CURLU *uh, struct Curl_easy *data,
      |                                     ~~~~~~~~~~~~~~~~~~^~~~
```

```
C:\a\curl\curl\lib\url.c(1777,55): warning C4100: 'data': unreferenced parameter [C:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
```