Revert "cm: unlock xcode workaround to all builds"
This reverts commit 701ef33de48f7fa74ad27729c86bdc4296f61600.

Needs more work, many targets fail, incuding the GNU Makefile
counterpart of the Xcode generator build:
```
[100%] Linking C executable units.app/units
cd /Users/runner/work/curl/curl/bld/tests/unit && /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/units.dir/link.txt --verbose=1
Undefined symbols for architecture arm64:
  "_hugehelp", referenced from:
      _operate in libcurltool.a[2](unity_0_c.c.o)
  "_showhelp", referenced from:
      _tool_help in libcurltool.a[2](unity_0_c.c.o)
      _tool_help in libcurltool.a[2](unity_0_c.c.o)
ld: symbol(s) not found for architecture arm64
```
https://github.com/curl/curl/actions/runs/12874833803/job/35895032436