lib1308.c res is a reserved var name used by first.h, untangle
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
In file included from libtests.c(125):
../../../tests/libtest/lib1308.c(52): error #188: enumerated type mixed with another type
    global_init(CURL_GLOBAL_ALL);
    ^
https://github.com/curl/curl/actions/runs/18561102955/job/52910049327?pr=19077#step:35:187