GHA/windows: drop MSH3 job (broken after 0.7.0 bump)
Starting GHA runner image 20250105.1.0.

```
C:\vcpkg\installed\x64-windows\include\msh3.h(150,13): error C2143: syntax error: missing ':' before 'constant' [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
C:\vcpkg\installed\x64-windows\include\msh3.h(150,13): error C2034: '<alignment member>': type of bit field too small for number of bits
C:\vcpkg\installed\x64-windows\include\msh3.h(150,22): error C2143: syntax error: missing ';' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(150,22): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(151,1): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(244,24): error C2143: syntax error: missing ')' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(244,24): error C2143: syntax error: missing '{' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(245,5): error C2370: 'uint32_t': redefinition; different storage class
      C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\stdint.h(24,28):
      see declaration of 'uint32_t'

C:\vcpkg\installed\x64-windows\include\msh3.h(245,14): error C2146: syntax error: missing ';' before identifier 'SettingsLength'
C:\vcpkg\installed\x64-windows\include\msh3.h(246,5): error C2059: syntax error: ')'
C:\vcpkg\installed\x64-windows\include\msh3.h(377,18): error C2143: syntax error: missing ':' before 'constant'
C:\vcpkg\installed\x64-windows\include\msh3.h(377,18): error C2034: '<alignment member>': type of bit field too small for number of bits
C:\vcpkg\installed\x64-windows\include\msh3.h(377,43): error C2143: syntax error: missing ';' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(377,43): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(378,43): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(378,43): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(379,43): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(379,43): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(380,43): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(380,43): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(381,43): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(381,43): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(384,9): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(408,5): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(409,1): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(416,23): error C2143: syntax error: missing ')' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(416,5): error C2081: 'MSH3_REQUEST_EVENT': name in formal parameter list illegal
C:\vcpkg\installed\x64-windows\include\msh3.h(416,23): error C2143: syntax error: missing '{' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(417,5): error C2059: syntax error: ')'
C:\vcpkg\installed\x64-windows\include\msh3.h(419,31): error C2143: syntax error: missing '{' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(425,41): error C2146: syntax error: missing ')' before identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(425,41): error C2061: syntax error: identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(425,41): error C2059: syntax error: ';'
C:\vcpkg\installed\x64-windows\include\msh3.h(425,48): error C2059: syntax error: ','
C:\vcpkg\installed\x64-windows\include\msh3.h(428,5): error C2059: syntax error: ')'
C:\vcpkg\installed\x64-windows\include\msh3.h(434,41): error C2146: syntax error: missing ')' before identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(434,41): error C2061: syntax error: identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(434,41): error C2059: syntax error: ';'
C:\vcpkg\installed\x64-windows\include\msh3.h(434,48): error C2059: syntax error: ','
C:\vcpkg\installed\x64-windows\include\msh3.h(436,5): error C2059: syntax error: ')'
C:\vcpkg\installed\x64-windows\include\msh3.h(494,18): error C2143: syntax error: missing ':' before 'constant'
C:\vcpkg\installed\x64-windows\include\msh3.h(494,18): error C2034: '<alignment member>': type of bit field too small for number of bits
C:\vcpkg\installed\x64-windows\include\msh3.h(494,38): error C2143: syntax error: missing ';' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(494,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(495,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(495,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(496,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(496,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(497,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(497,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(498,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(498,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(499,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(499,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(500,38): error C2143: syntax error: missing '{' before ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(500,38): error C2059: syntax error: ':'
C:\vcpkg\installed\x64-windows\include\msh3.h(501,9): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(507,5): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(508,1): error C2059: syntax error: '}'
C:\vcpkg\installed\x64-windows\include\msh3.h(515,24): error C2143: syntax error: missing ')' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(515,5): error C2081: 'MSH3_LISTENER_EVENT': name in formal parameter list illegal
C:\vcpkg\installed\x64-windows\include\msh3.h(515,24): error C2143: syntax error: missing '{' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(516,5): error C2059: syntax error: ')'
C:\vcpkg\installed\x64-windows\include\msh3.h(518,32): error C2143: syntax error: missing '{' before '*'
C:\vcpkg\installed\x64-windows\include\msh3.h(525,42): error C2146: syntax error: missing ')' before identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(525,42): error C2061: syntax error: identifier 'Handler'
C:\vcpkg\installed\x64-windows\include\msh3.h(525,42): error C2059: syntax error: ';'
C:\vcpkg\installed\x64-windows\include\msh3.h(525,49): error C2059: syntax error: ','
C:\vcpkg\installed\x64-windows\include\msh3.h(527,5): error C2059: syntax error: ')'
D:\a\curl\curl\lib\vquic\curl_msh3.c(276,1): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
D:\a\curl\curl\lib\vquic\curl_msh3.c(276,33): error C2061: syntax error: identifier 'msh3_conn_if'
D:\a\curl\curl\lib\vquic\curl_msh3.c(276,33): error C2059: syntax error: ';'
D:\a\curl\curl\lib\vquic\curl_msh3.c(276,46): error C2513: ' ': no variable declared before '='
D:\a\curl\curl\lib\vquic\curl_msh3.c(280,2): warning C4218: nonstandard extension used: must specify at least a storage class or a type
D:\a\curl\curl\lib\vquic\curl_msh3.c(318,1): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
D:\a\curl\curl\lib\vquic\curl_msh3.c(318,30): error C2061: syntax error: identifier 'msh3_request_if'
D:\a\curl\curl\lib\vquic\curl_msh3.c(318,30): error C2059: syntax error: ';'
D:\a\curl\curl\lib\vquic\curl_msh3.c(318,46): error C2513: ' ': no variable declared before '='
D:\a\curl\curl\lib\vquic\curl_msh3.c(324,2): warning C4218: nonstandard extension used: must specify at least a storage class or a type
D:\a\curl\curl\lib\vquic\curl_msh3.c(680,19): warning C4013: 'MsH3RequestOpen' undefined; assuming extern returning int
D:\a\curl\curl\lib\vquic\curl_msh3.c(680,48): error C2065: 'msh3_request_if': undeclared identifier
D:\a\curl\curl\lib\vquic\curl_msh3.c(682,41): error C2065: 'MSH3_REQUEST_FLAG_FIN': undeclared identifier
D:\a\curl\curl\lib\vquic\curl_msh3.c(680,17): warning C4047: '=': 'MSH3_REQUEST *' differs in levels of indirection from 'int'
D:\a\curl\curl\lib\vquic\curl_msh3.c(700,9): error C2198: 'bool MsH3RequestSend(MSH3_REQUEST *,MSH3_REQUEST_SEND_FLAGS,const MSH3_HEADER *,size_t,const void *,uint32_t,void *)': too few arguments for call
D:\a\curl\curl\lib\vquic\curl_msh3.c(807,42): error C2065: 'MSH3_REQUEST_FLAG_FIN': undeclared identifier
D:\a\curl\curl\lib\vquic\curl_msh3.c(808,29): warning C4133: 'function': incompatible types - from 'char [1]' to 'const MSH3_HEADER *'
D:\a\curl\curl\lib\vquic\curl_msh3.c(807,13): error C2198: 'bool MsH3RequestSend(MSH3_REQUEST *,MSH3_REQUEST_SEND_FLAGS,const MSH3_HEADER *,size_t,const void *,uint32_t,void *)': too few arguments for call
D:\a\curl\curl\lib\vquic\curl_msh3.c(863,36): error C2065: 'msh3_conn_if': undeclared identifier
D:\a\curl\curl\lib\vquic\curl_msh3.c(863,35): warning C4047: 'function': 'const MSH3_CONNECTION_CALLBACK_HANDLER' differs in levels of indirection from 'int *'
D:\a\curl\curl\lib\vquic\curl_msh3.c(863,35): warning C4024: 'MsH3ConnectionOpen': different types for formal and actual parameter 2
D:\a\curl\curl\lib\vquic\curl_msh3.c(865,49): error C2197: 'MSH3_CONNECTION *MsH3ConnectionOpen(MSH3_API *,const MSH3_CONNECTION_CALLBACK_HANDLER,void *)': too many arguments for call
D:\a\curl\curl\lib\vquic\curl_msh3.c(866,35): error C2197: 'MSH3_CONNECTION *MsH3ConnectionOpen(MSH3_API *,const MSH3_CONNECTION_CALLBACK_HANDLER,void *)': too many arguments for call
D:\a\curl\curl\lib\vquic\curl_msh3.c(867,35): error C2197: 'MSH3_CONNECTION *MsH3ConnectionOpen(MSH3_API *,const MSH3_CONNECTION_CALLBACK_HANDLER,void *)': too many arguments for call
```
Ref: https://github.com/curl/curl/actions/runs/12653247149/job/35258053847#step:9:29

Bug: https://github.com/curl/curl/pull/15924#issuecomment-2575106711