x509asn1: try fixing missing declaration
```
Users/runner/work/curl/curl/tests/unit/unit1666.c:50:12: error: call to undeclared function 'encodeOID'; ISO C99 and later do not support implicit function declarations [clang-diagnostic-implicit-function-declaration]
Suppressed 20576 warnings (20514 in non-user code, 62 with check filters).
Use -header-filter=.* or leave it as default to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
   50 |   result = encodeOID(dbuf, oid, oid + spec->size);
      |            ^
```
https://github.com/curl/curl/actions/runs/23297585193/job/67749143844?pr=21008