fix static name collisions in debug builds
```
C:/projects/curl/lib/hsts.c(60,15): error C2084: function 'time_t debugtime(void *)' already has a body [C:\projects\curl\lib\libcurl.vcxproj]
C:/projects/curl/lib/altsvc.c(427,15): message : see previous definition of 'debugtime' [C:\projects\curl\lib\libcurl.vcxproj]
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/47218733/job/fxt21ujjnckls1dc#L237

```
In file included from C:/projects/curl/lib/CMakeFiles/libcurl.dir/Unity/unity_0.c:64:0:
C:/projects/curl/lib/hsts.c:60:15: error: redefinition of 'debugtime'
 static time_t debugtime(void *unused)
               ^~~~~~~~~
In file included from C:/projects/curl/lib/CMakeFiles/libcurl.dir/Unity/unity_0.c:3:0:
C:/projects/curl/lib/altsvc.c:427:15: note: previous definition of 'debugtime' was here
 static time_t debugtime(void *unused)
               ^~~~~~~~~
In file included from C:/projects/curl/lib/CMakeFiles/libcurl.dir/Unity/unity_0.c:110:0:
C:/projects/curl/lib/socks.c: In function 'socksstate':
C:/projects/curl/lib/socks.c:164:29: error: declaration of 'statename' shadows a global declaration [-Werror=shadow]
   static const char * const statename[] = {
                             ^~~~~~~~~
In file included from C:/projects/curl/lib/CMakeFiles/libcurl.dir/Unity/unity_0.c:88:0:
C:/projects/curl/lib/multi.c:115:27: note: shadowed declaration is here
 static const char * const statename[]={
                           ^~~~~~~~~
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/47218733/job/htg2pm8276olu0vp#L245