Revert "unit1309: replace macro with scoped constant"
This reverts commit 2a6c0d568c922fdb564a7de25a575a7d1c04d391.

nope:
```
In file included from /home/runner/work/curl/curl/bld/tests/unit/unit_bundle.c:31,
                 from /home/runner/work/curl/curl/bld/tests/unit/CMakeFiles/units.dir/Unity/unity_0_c.c:4:
/home/runner/work/curl/curl/tests/unit/unit1309.c: In function ‘test_unit1309’:
/home/runner/work/curl/curl/tests/unit/unit1309.c:68:10: error: ISO C90 forbids variable length array ‘nodes’ [-Werror=vla]
   68 |   struct Curl_tree nodes[num_nodes*3];
      |          ^~~~~~~~~
/home/runner/work/curl/curl/tests/unit/unit1309.c:69:3: error: ISO C90 forbids variable length array ‘storage’ [-Werror=vla]
   69 |   size_t storage[num_nodes*3];
      |   ^~~~~~
```