server: sync timediff_t type across modules
fix unused timediff warning with clang-cl

```
C:/projects/curl/tests/server/util.c(463,13): error : unused function 'timediff' [-Werror,-Wunused-function]
```
https://ci.appveyor.com/project/curlorg/curl/builds/51606010/job/p1e4tmsahj0p043r#L208