cm fix macro error causing clang-tidy error
```
[...] -I/Users/runner/work/curl/curl/lib -I/Users/runner/work/curl/curl/tests/client -DCURL_HIDDEN_SYMBOLS -DHAVE_CONFIG_H -D_definitions_t-NOTFOUND
```
error: ISO C99 requires whitespace after the macro name [clang-diagnostic-c99-extensions,-warnings-as-errors]