Revert "cli_hx_download.c merge two printfs"
This reverts commit 4c4cc41a26953198ddbf29a966386b2d34ba1931.

```
../../../tests/libtest/cli_hx_download.c:268:3: error: string length ‘626’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
  268 |   );
      |   ^
```