schannel: drop unused assigment
https://github.com/curl/curl/actions/runs/13969308325/job/39106970359?pr=16764#step:8:612
```
/home/runner/work/curl/curl/lib/vtls/schannel.c:1944:7: error: Value stored to 'nread' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
 1944 |       nread = -1;
      |       ^       ~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1944:7: note: Value stored to 'nread' is never read
 1944 |       nread = -1;
      |       ^       ~~
```