cmake: fix `sys/utime.h` detection on AmigaOS
It requires `sys/time.h` to avoid:
```
        /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/sys-include/sys/utime.h:14:3: error: unknown type name 'time_t'
           time_t actime;
           ^~~~~~
        /opt/appveyor/build-agent/opt/amiga/m68k-amigaos/sys-include/sys/utime.h:15:3: error: unknown type name 'time_t'
           time_t modtime;
           ^~~~~~
```