server/mqttd: try fixing bogus-looking VS2019 32-bit compiler warning
Visual Studio Community 2019 version 16.11.50:
```
-- Building for: Visual Studio 16 2019
-- Using CMake version 4.1.0
-- curl version=[8.23.0-DEV]
-- Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.29.30159.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
-- CMake platform flags: WIN32 MSVC-1929
[...]
-- Found _WIN32_WINNT=0x0a00
-- Picky compiler options: -W4 -Wall -wd4061 -wd4191 -wd4255 -wd4464 -wd4548 -wd4574 -wd4668 -wd4710 -wd4711 -wd4746 -wd4820 -wd5045
[...]
tests\server\mqttd.c(169,19): error C2220: the following warning is treated as an error
tests\server\mqttd.c(169,19): warning C4777: 'fprintf' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'size_t'
tests\server\mqttd.c(169,19): message : the sizes of types 'size_t' and 'unsigned int' might differ on other platforms
tests\server\mqttd.c(169,19): message : consider using '%zx' in the format string
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/54855420/job/71ccddu696xhn95q#L263