cm use `-Wno-nonportable-system-include-path` with clang-cl
This is not a useful warning. There is no standard casing for these
headers. Some SDKs (MS) use the camel-cased style, some the fully
lowercase one (mingw-w64/wine). Source always uses the lower-case ones,
because it doesn't matter on Windows, and in most cross-build cases,
the toolchain also provides lower-case names. One rare exception is
when building with clang-cl on a case-sensitive filesystem (Linux)
while using the MS provided SDK headers, e.g. via
the https://github.com/mstorsjo/msvc-wine project. In this case the
project will lowercase these filenames with a dedicated script, AFAICS,
though I haven't tested it on a case-sensitive FS yet.

```
  Building Custom Rule C:/projects/curl/lib/CMakeLists.txt
  In file included from C:\projects\curl\_bld\lib\CMakeFiles\libcurl_object.dir\Unity\unity_0_c.c:4:
  In file included from C:/projects/curl/lib/altsvc.c:28:
  In file included from C:/projects/curl/lib\curl_setup.h:326:
C:/projects/curl/lib\setup-win32.h(80,12): error : non-portable path to file '<WinSock2.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-system-include-path]
C:/projects/curl/lib\setup-win32.h(81,12): error : non-portable path to file '<WS2tcpip.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-system-include-path]
C:/projects/curl/lib\setup-win32.h(82,12): error : non-portable path to file '<Windows.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-system-include-path]
```
https://ci.appveyor.com/project/curlorg/curl/builds/52704235/job/gvrpvr3v8ta47ish