mbedtls: re-add an error check
While adding support for key blobs, this check got pushed after some
logic and its update to the error code was no longer checked.

Detected by clang-tidy:
```
Users/runner/work/curl/curl/lib/vtls/mbedtls.c:768:7: error: Value stored to 'ret' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  768 |       ret = MBEDTLS_ERR_PK_TYPE_MISMATCH;
      |       ^
```
https://github.com/curl/curl/actions/runs/13953249156/job/39057979349?pr=16764#step:12:178

Regression from 05e0453050def7323fbc8210886f909819edcc5f #7157