examples: make it compile with wince
```
/Users/runner/work/curl/curl/docs/examples/anyauthput.c: In function 'main':
/Users/runner/work/curl/curl/docs/examples/anyauthput.c:106: error: passing argument 1 of '_fstat' makes integer from pointer without a cast
/Users/runner/opt/mingw32ce/bin/../lib/gcc/arm-mingw32ce/4.4.0/../../../../arm-mingw32ce/include/sys/stat.h:159: note: expected 'int' but argument is of type 'void *'
```
https://github.com/curl/curl/actions/runs/12737284422/job/35498141686#step:11:27

examples: prefer UNDER_CE

It's defined by the compiler. `_WIN32_WCE` requires `windef.h`
via one of the system headers. This made it accidental in case
of standalone programs.