first.c: try fixing bogus Intel compiler warning
```
first.c(204): error #592: variable "test_id" is used before its value is set
    (void)test_id;
          ^
compilation aborted for first.c (code 2)
```
Ref: https://github.com/curl/curl/actions/runs/10693309076/job/29643258913?pr=14772#step:39:549