cmake-config: define CURL::win32_winsock
To avoid:
```
-- Configuring done (2.1s)
CMake Error at bld-curl/_pkg/lib/cmake/CURL/CURLTargets.cmake:61 (set_target_properties):
  The link interface of target "CURL::libcurl_static" contains:

    CURL::win32

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  bld-curl/_pkg/lib/cmake/CURL/CURLConfig.cmake:157 (include)
  CMakeLists.txt:48 (find_package)

CMake Generate step failed.  Build files cannot be regenerated correctly.
-- Generating done (0.0s)
Error: Process completed with exit code 1.
```
https://github.com/curl/curl/actions/runs/14626700644/job/41039814355?pr=16973#step:7:247

In Windows integration tests, when consuming libcurl via `find_package()`.