system_win32: try fix for UWP missing GetModuleHandleA
Build-tested only.

```
curl/lib/system_win32.c: In function 'Curl_win32_init':
curl/lib/system_win32.c:115:15: error: implicit declaration of function 'GetModuleHandleA'; did you mean 'GetModuleFileNameA'? [-Wimplicit-function-declaration]
  115 |   ws2_32Dll = GetModuleHandleA("ws2_32");
      |               ^~~~~~~~~~~~~~~~
      |               GetModuleFileNameA
curl/lib/system_win32.c:115:15: error: nested extern declaration of 'GetModuleHandleA' [-Werror=nested-externs]
curl/lib/system_win32.c:115:13: error: assignment to 'HMODULE' {aka 'struct HINSTANCE__ *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  115 |   ws2_32Dll = GetModuleHandleA("ws2_32");
      |             ^
```
Ref: https://github.com/curl/curl/actions/runs/9359109770/job/25762248493#step:12:24