tool_doswin: disable GetLoadedModulePaths for uwp
apparently mingw-w64 is okay with this, but the official SDK headers
are not:
```
src\tool_doswin.c(620,3): error C2065: 'MODULEENTRY32': undeclared identifier
src\tool_doswin.c(620,17): error C2146: syntax error: missing ';' before identifier 'mod'
src\tool_doswin.c(620,17): error C2065: 'mod': undeclared identifier
src\tool_doswin.c(620,23): error C2059: syntax error: '{'
src\tool_doswin.c(623,3): error C2065: 'mod': undeclared identifier
src\tool_doswin.c(623,7): error C2224: left of '.dwSize' must have struct/union type
src\tool_doswin.c(623,23): error C2065: 'MODULEENTRY32': undeclared identifier
src\tool_doswin.c(626,11): warning C4013: 'CreateToolhelp32Snapshot' undefined; assuming extern returning int
src\tool_doswin.c(626,36): error C2065: 'TH32CS_SNAPMODULE': undeclared identifier
src\tool_doswin.c(626,9): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
src\tool_doswin.c(632,7): warning C4013: 'Module32First' undefined; assuming extern returning int
src\tool_doswin.c(632,27): error C2065: 'mod': undeclared identifier
src\tool_doswin.c(642,24): error C2065: 'mod': undeclared identifier
src\tool_doswin.c(642,28): error C2224: left of '.szExePath' must have struct/union type
src\tool_doswin.c(642,42): error C2056: illegal expression
src\tool_doswin.c(642,17): error C2466: cannot allocate an array of constant size 0
src\tool_doswin.c(642,10): error C2133: 'buffer': unknown size
src\tool_doswin.c(643,40): error C2065: 'mod': undeclared identifier
src\tool_doswin.c(643,44): error C2224: left of '.szExePath' must have struct/union type
src\tool_doswin.c(643,55): warning C4047: 'function': 'LPCWCH' differs in levels of indirection from 'int'
src\tool_doswin.c(643,55): warning C4024: 'WideCharToMultiByte': different types for formal and actual parameter 3
src\tool_doswin.c(644,29): warning C4047: 'function': 'int' differs in levels of indirection from 'char [0]'
src\tool_doswin.c(644,29): warning C4024: 'WideCharToMultiByte': different types for formal and actual parameter 4
src\tool_doswin.c(644,37): warning C4034: sizeof returns 0
src\tool_doswin.c(644,53): warning C4047: 'function': 'int' differs in levels of indirection from 'void *'
src\tool_doswin.c(644,53): warning C4024: 'WideCharToMultiByte': different types for formal and actual parameter 6
src\tool_doswin.c(643,9): error C2198: 'int WideCharToMultiByte(UINT,DWORD,LPCWCH,int,LPSTR,int,LPCCH,LPBOOL)': too few arguments for call
src\tool_doswin.c(654,11): warning C4013: 'Module32Next' undefined; assuming extern returning int
src\tool_doswin.c(654,30): error C2065: 'mod': undeclared identifier
```
https://github.com/curl/curl/actions/runs/12055081933/job/33614629930#step:9:35