sync with configure to avoid Intel C warning
```
conftest.c(38): error: #error directive: force compilation error
          #error force compilation error
           ^

conftest.c(40): warning #1011: missing return statement at end of non-void function "main"
        }
        ^
```