am: unity fix local macro clashing with OmniOS
```
In file included from ../../lib/urldata.h:197,
                   from ../../lib/altsvc.c:32,
                   from libcurlall.c:2:
  ../../lib/cf-socket.h:55:25: error: expected ':', ',', ';', '}' or '__attribute__' before '.' token
     55 | #define sa_addr _sa_ex_u.addr
        |                         ^
  In file included from ../../lib/urldata.h:197,
                   from ../../lib/altsvc.c:32,
                   from libcurlall.c:2:
  ../../lib/cf-socket.h:55:25: error: expected ':', ',', ';', '}' or '__attribute__' before '.' token
     55 | #define sa_addr _sa_ex_u.addr
        |                         ^
```
Ref: https://github.com/curl/curl/actions/runs/10738314933/job/29781644299?pr=14772#step:3:6115