Fix to get cyassl's NO_FILESYSTEM to work with libcurl-7.21.6 and cyassl 1.9.0
Otherwise I'd get linker errors for the missing "SSL_CTX_load_verify_locations" functions:

--snip-- Debug/libcurl.lib(cyassl.obj): In function `cyassl_connect_step1':
--snip-- external/curl-7.21.6/lib/cyassl.c(127): undefined reference to `.SSL_CTX_load_verify_locations'
--snip-- external/curl-7.21.6/lib/cyassl.c(164): undefined reference to `.SSL_CTX_use_certificate_file'
--snip-- external/curl-7.21.6/lib/cyassl.c(172): undefined reference to `.SSL_CTX_use_PrivateKey_file'