m4/curl-wolfssl.m4: fix build with older wolfSSL
Commit 0159100f4f78 ("lib: use (u)int64_t instead of long long") removed
definition of SIZEOF_LONG_LONG for wolfSSL. This breaks autotools build
for wolfSSL version 5.7.2 at least:

In file included from .../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/hash.h:29,
                 from .../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/openssl/md5.h:32,
                 from md5.c:76:
.../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1289:10: error: #error "bad math long / long long settings"
 1289 |         #error "bad math long / long long settings"
      |          ^~~~~
.../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1291:5: error: empty enum is invalid
 1291 |     };
      |     ^
make[3]: *** [Makefile:2966: libcurl_la-md5.lo] Error 1

Restore SIZEOF_LONG_LONG macro definition to fix the build.