am: try workaround for missing `in6addr_any` in tests/server
```
D:/a/_temp/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
  socksd-socksd.o:socksd.c:(.rdata$.refptr.in6addr_any[.refptr.in6addr_any]+0x0): undefined reference to `in6addr_any'
```
https://github.com/curl/curl/actions/runs/12810353428/job/35717243068?pr=16019#step:12:182