pytest: adjust threshold in test_20_11_crazy_pings to better pass on arm64
Seen with GHA/http3-linux BoringSSL since moving from x64 to arm64:
```
>       assert (rss1 * 1.2) > rss2, 'bad memory increase'
E       AssertionError: bad memory increase
E       assert (10.15625 * 1.2) > 12.2734375

../../tests/http/test_20_websockets.py:330: AssertionError
```
Ref: https://github.com/curl/curl/actions/runs/37599901852/job/112721784104?pr=23294#step:32:2093

```
>       assert (rss1 * 1.2) > rss2, 'bad memory increase'
E       AssertionError: bad memory increase
E       assert (10.16015625 * 1.2) > 12.390625

../../tests/http/test_20_websockets.py:330: AssertionError
```
Ref: https://github.com/curl/curl/actions/runs/37555944489/job/112582218973#step:32:2093

Follow-up to 82b289c9527890a0766b55be2214b3749283307a #22574
Follow-up to 849317ff5c5a5e13f50ec3d001e46ddffa77d8a4 #21911

Closes #23298