move math lib logic to WolfSSL
It's required by wolfSSL:
```
FAILED: src/curl
: && /usr/bin/cc -fPIC  -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wsign-conversion -Wno-error=sign-conversion -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wstrict-aliasing=3 -Wtrampolines -Wformat=2 -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Warith-conversion -Wdouble-promotion -Wenum-conversion -Wpragmas -Wunused-const-variable -g  src/CMakeFiles/curl.dir/slist_wc.c.o src/CMakeFiles/curl.dir/terminal.c.o src/CMakeFiles/curl.dir/tool_binmode.c.o src/CMakeFiles/curl.dir/tool_bname.c.o src/CMakeFiles/curl.dir/tool_cb_dbg.c.o src/CMakeFiles/curl.dir/tool_cb_hdr.c.o src/CMakeFiles/curl.dir/tool_cb_prg.c.o src/CMakeFiles/curl.dir/tool_cb_rea.c.o src/CMakeFiles/curl.dir/tool_cb_see.c.o src/CMakeFiles/curl.dir/tool_cb_soc.c.o src/CMakeFiles/curl.dir/tool_cb_wrt.c.o src/CMakeFiles/curl.dir/tool_cfgable.c.o src/CMakeFiles/curl.dir/tool_dirhie.c.o src/CMakeFiles/curl.dir/tool_doswin.c.o src/CMakeFiles/curl.dir/tool_easysrc.c.o src/CMakeFiles/curl.dir/tool_filetime.c.o src/CMakeFiles/curl.dir/tool_findfile.c.o src/CMakeFiles/curl.dir/tool_formparse.c.o src/CMakeFiles/curl.dir/tool_getparam.c.o src/CMakeFiles/curl.dir/tool_getpass.c.o src/CMakeFiles/curl.dir/tool_help.c.o src/CMakeFiles/curl.dir/tool_helpers.c.o src/CMakeFiles/curl.dir/tool_hugehelp.c.o src/CMakeFiles/curl.dir/tool_ipfs.c.o src/CMakeFiles/curl.dir/tool_libinfo.c.o src/CMakeFiles/curl.dir/tool_listhelp.c.o src/CMakeFiles/curl.dir/tool_main.c.o src/CMakeFiles/curl.dir/tool_msgs.c.o src/CMakeFiles/curl.dir/tool_operate.c.o src/CMakeFiles/curl.dir/tool_operhlp.c.o src/CMakeFiles/curl.dir/tool_paramhlp.c.o src/CMakeFiles/curl.dir/tool_parsecfg.c.o src/CMakeFiles/curl.dir/tool_progress.c.o src/CMakeFiles/curl.dir/tool_setopt.c.o src/CMakeFiles/curl.dir/tool_sleep.c.o src/CMakeFiles/curl.dir/tool_stderr.c.o src/CMakeFiles/curl.dir/tool_strdup.c.o src/CMakeFiles/curl.dir/tool_urlglob.c.o src/CMakeFiles/curl.dir/tool_util.c.o src/CMakeFiles/curl.dir/tool_vms.c.o src/CMakeFiles/curl.dir/tool_writeout.c.o src/CMakeFiles/curl.dir/tool_writeout_json.c.o src/CMakeFiles/curl.dir/tool_xattr.c.o src/CMakeFiles/curl.dir/var.c.o src/CMakeFiles/curl.dir/__/lib/base64.c.o src/CMakeFiles/curl.dir/__/lib/dynbuf.c.o -o src/curl  lib/libcurl-d.a  /home/tal/vcpkg/installed/x64-linux/debug/lib/libwolfssl.a  /home/tal/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/tal/vcpkg/installed/x64-linux/debug/lib/libngtcp2.a  /home/tal/vcpkg/installed/x64-linux/debug/lib/libngtcp2_crypto_wolfssl.a  /home/tal/vcpkg/installed/x64-linux/debug/lib/libnghttp3.a && :
/usr/bin/ld: /home/tal/vcpkg/installed/x64-linux/debug/lib/libwolfssl.a(dh.c.o): in function `DiscreteLogWorkFactor':
/home/tal/vcpkg/buildtrees/wolfssl/src/7.2-stable-e61253ad9d.clean/wolfcrypt/src/dh.c:1031: undefined reference to `pow'
/usr/bin/ld: /home/tal/vcpkg/buildtrees/wolfssl/src/7.2-stable-e61253ad9d.clean/wolfcrypt/src/dh.c:1032: undefined reference to `log'
/usr/bin/ld: /home/tal/vcpkg/buildtrees/wolfssl/src/7.2-stable-e61253ad9d.clean/wolfcrypt/src/dh.c:1032: undefined reference to `pow'
```
Ref: #14343