document feature missing from current mingw-w64 in UWP mode
https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-pfximportcertstore

```
D:/a/curl/curl/lib/vtls/schannel.c: In function 'schannel_acquire_credential_handle':
D:/a/curl/curl/lib/vtls/schannel.c:651:24: error: implicit declaration of function 'PFXImportCertStore' [-Wimplicit-function-declaration]
  651 |           cert_store = PFXImportCertStore(&datablob, pszPassword,
      |                        ^~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/vtls/schannel.c:651:24: error: nested extern declaration of 'PFXImportCertStore' [-Werror=nested-externs]
D:/a/curl/curl/lib/vtls/schannel.c:651:22: error: assignment to 'HCERTSTORE' {aka 'void *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  651 |           cert_store = PFXImportCertStore(&datablob, pszPassword,
      |                      ^
D:/a/curl/curl/lib/vtls/schannel.c:654:22: error: assignment to 'HCERTSTORE' {aka 'void *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  654 |           cert_store = PFXImportCertStore(&datablob, pszPassword, 0);
      |                      ^
D:/a/curl/curl/lib/vtls/schannel.c:717:11: error: implicit declaration of function 'CryptStringToBinary' [-Wimplicit-function-declaration]
  717 |       if(!CryptStringToBinary(cert_thumbprint_str,
      |           ^~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/vtls/schannel.c:717:11: error: nested extern declaration of 'CryptStringToBinary' [-Werror=nested-externs]
D:/a/curl/curl/lib/vtls/schannel.c:719:31: error: 'CRYPT_STRING_HEX' undeclared (first use in this function)
  719 |                               CRYPT_STRING_HEX,
      |                               ^~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/vtls/schannel.c:719:31: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: all warnings being treated as errors
```
https://github.com/curl/curl/actions/runs/16603975843/job/46970895223?pr=18085#step:10:24