fix missing declaration
lib/sha256.c:506:26: error: variable has incomplete type 'const struct HMAC_params'
  506 | const struct HMAC_params Curl_HMAC_SHA256 = {
      |                          ^
lib/curl_sha256.h:34:21: note: forward declaration of 'struct HMAC_params'
   34 | extern const struct HMAC_params Curl_HMAC_SHA256;
      |                     ^
1 error generated.

-DCURL_DISABLE_AWS=ON -DCURL_DISABLE_DIGEST_AUTH=ON -DCURL_ENABLE_SSL=OFF + libssh2