hostip: fix unity + c-ares + HTTPS-RR builds
Fixing (as seen in curl-for-win dev branch):
```
In file included from _a64-linux-gnu-bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_1_c.c:85:
lib/hostip.c:1473:10: error: redefinition of 'CURLE_NOT_BUILT_IN' as different kind of symbol
 1473 | CURLcode Curl_resolv_check(struct Curl_easy *data,
      |          ^
lib/hostip.h:195:33: note: expanded from macro 'Curl_resolv_check'
  195 | #define Curl_resolv_check(x, y) CURLE_NOT_BUILT_IN
      |                                 ^
include/curl/curl.h:523:3: note: previous definition is here
  523 |   CURLE_NOT_BUILT_IN,            /* 4 - [was obsoleted in August 2007 for
      |   ^
In file included from _a64-linux-gnu-bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_1_c.c:85:
lib/hostip.c:1474:56: error: expected ';' after top level declarator
 1474 |                            struct Curl_dns_entry **dns)
      |                                                        ^
      |                                                        ;
2 errors generated.
```

Root cause may be a discrepancy in the `USE_CURL_ASYNC` value as set in
hostip.h vs. in hostip.c, but couldn't spot an obvious culprit.

Cherry-picked from #21032