mbedtls: Guard TLS 1.3 + session tickets usage inside ifdef
If TLS 1.3 is not supported, the call to
`mbedtls_ssl_conf_tls13_enable_signal_new_session_tickets()`
will fail during compilation:

  ../../curl-8.18.0/lib/vtls/mbedtls.c: In function 'mbed_connect_step1':
  ../../curl-8.18.0/lib/vtls/mbedtls.c:809:3: error: implicit declaration of function 'mbedtls_ssl_conf_tls13_enable_signal_new_session_tickets' [-Werror=implicit-function-declaration]
     mbedtls_ssl_conf_tls13_enable_signal_new_session_tickets(&backend->config,
     ^
  ../../curl-8.18.0/lib/vtls/mbedtls.c:809:3: warning: nested extern declaration of 'mbedtls_ssl_conf_tls13_enable_signal_new_session_tickets' [-Wnested-externs]

Protect this call inside the `#ifdef` block by making sure
that support for TLS 1.3 is defined.

Signed-off-by: Daniel Díaz <daniel.diaz@sonos.com>