unit1660: fix unreachable code warning in no-ssl builds
```
C:\projects\curl\tests\unit\unit1660.c(46,1): error C2220: the following warning is treated as an error [C:\projects\curl\_bld\tests\unit\units.vcxproj]
C:\projects\curl\tests\unit\unit1660.c(46,1): warning C4702: unreachable code
```
Ref: https://ci.appveyor.com/project/curlorg/curl/builds/50531210/job/cjewvo9agavthr3o#L216

Required-by: #14922
Cherry-picked from #14772