idn: fix warning in certain mingw-w64 env
All mingw-w64 versions declare these IDN function, but some mingw-envs
set the default _WIN32_WINNT value conservatively, e.g. to 0x0502. In
such case idn.c was assuming an old SDK env, assumed these declarations
missing and declared them. This caused duplicate declaration warnings.
Fix it by always skipping local declarations for mingw builds. (Classic
mingw may fail on that, but curl no longer supports classic mingw)

I'm not sure why this wasn't happening with cmake builds in the same
build env.

Seen on Ubuntu mingw-w64 cross-builds.

```
../../lib/idn.c:154:23: error: redundant redeclaration of ‘IdnToAscii’ [-Werror=redundant-decls]
  154 | WINBASEAPI int WINAPI IdnToAscii(DWORD dwFlags,
      |                       ^~~~~~~~~~
In file included from /usr/share/mingw-w64/include/windows.h:73,
                 from /usr/share/mingw-w64/include/winsock2.h:23,
                 from ../../lib/setup-win32.h:91,
                 from ../../lib/curl_setup.h:308,
                 from ../../lib/idn.c:29:
/usr/share/mingw-w64/include/winnls.h:1075:30: note: previous declaration of ‘IdnToAscii’ was here
 1075 |   WINNORMALIZEAPI int WINAPI IdnToAscii (DWORD dwFlags, LPCWSTR lpUnicodeCharStr, int cchUnicodeChar, LPWSTR lpASCIICharStr, int cchASCIIChar);
      |                              ^~~~~~~~~~
../../lib/idn.c:159:23: error: redundant redeclaration of ‘IdnToUnicode’ [-Werror=redundant-decls]
  159 | WINBASEAPI int WINAPI IdnToUnicode(DWORD dwFlags,
      |                       ^~~~~~~~~~~~
In file included from /usr/share/mingw-w64/include/windows.h:73,
                 from /usr/share/mingw-w64/include/winsock2.h:23,
                 from ../../lib/setup-win32.h:91,
                 from ../../lib/curl_setup.h:308,
                 from ../../lib/idn.c:29:
/usr/share/mingw-w64/include/winnls.h:1077:30: note: previous declaration of ‘IdnToUnicode’ was here
 1077 |   WINNORMALIZEAPI int WINAPI IdnToUnicode (DWORD dwFlags, LPCWSTR lpASCIICharStr, int cchASCIIChar, LPWSTR lpUnicodeCharStr, int cchUnicodeChar);
      |                              ^~~~~~~~~~~~
```
Ref: https://github.com/curl/curl/actions/runs/10548869067/job/29223257811?pr=14680#step:7:90