tool_doswin: drop unused assigment
https://github.com/curl/curl/actions/runs/13972569875/job/39118035675?pr=16764#step:8:214
```
home/runner/work/curl/curl/src/tool_doswin.c:180:7: error: Value stored to 'len' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  180 |       len = clip - target;
      |       ^     ~~~~~~~~~~~~~
1 warning generated.
```