unit1395: fix `argument is null` and related issues
- stop calling `strcmp()` with NULL to avoid undefined behaviour.
- fix checking results if some of them were NULL.
- do not pass NULL to printf `%s`.

```
In file included from ../../tests/libtest/test.h:43,
                 from curlcheck.h:24,
                 from unit1395.c:24:
unit1395.c: In function ‘test’:
../../lib/curl_printf.h:44:18: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
   44 | # define fprintf curl_mfprintf
unit1395.c:93:7: note: in expansion of macro ‘fprintf’
   93 |       fprintf(stderr, "Test %u: '%s' gave '%s' instead of NULL\n",
      |       ^~~~~~~
```
Ref: https://github.com/curl/curl/actions/runs/6896854253/job/18763836775?pr=12346#step:33:1689