try something 1 for mingw-w64 build
CMAKE_SYSTEM_VERSION is only effective for MSVC, and we also need to
set this for autotools, so just stick with _WIN32_WINNT.

Necessary to enable BCryptGenRandom() in mingw-w64 headers since mingw-w64 v6.0.

```
D:/a/curl/curl/lib/rand.c:49:6: error: implicit declaration of function 'BCryptGenRandom' [-Wimplicit-function-declaration]
   49 |   if(BCryptGenRandom(NULL, entropy, (ULONG)length,
      |      ^~~~~~~~~~~~~~~
D:/a/curl/curl/lib/rand.c:49:6: error: nested extern declaration of 'BCryptGenRandom' [-Werror=nested-externs]
D:/a/curl/curl/lib/rand.c:50:22: error: 'BCRYPT_USE_SYSTEM_PREFERRED_RNG' undeclared (first use in this function)
   50 |                      BCRYPT_USE_SYSTEM_PREFERRED_RNG) != STATUS_SUCCESS)
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/rand.c:50:22: note: each undeclared identifier is reported only once for each function it appears in
D:/a/curl/curl/lib/rand.c:42:26: error: 'NTSTATUS' undeclared (first use in this function); did you mean 'LSTATUS'?
   42 | #define STATUS_SUCCESS ((NTSTATUS)0x00000000L)
      |                          ^~~~~~~~
D:/a/curl/curl/lib/rand.c:50:58: note: in expansion of macro 'STATUS_SUCCESS'
   50 |                      BCRYPT_USE_SYSTEM_PREFERRED_RNG) != STATUS_SUCCESS)
      |                                                          ^~~~~~~~~~~~~~
D:/a/curl/curl/lib/rand.c:42:35: error: expected ')' before numeric constant
   42 | #define STATUS_SUCCESS ((NTSTATUS)0x00000000L)
      |                        ~          ^~~~~~~~~~~
D:/a/curl/curl/lib/rand.c:50:58: note: in expansion of macro 'STATUS_SUCCESS'
   50 |                      BCRYPT_USE_SYSTEM_PREFERRED_RNG) != STATUS_SUCCESS)
      |                                                          ^~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
```
https://github.com/curl/curl/actions/runs/23246552140/job/67576489473?pr=20983