vtls_scache.c unused vars
lib/vtls/vtls_scache.c:1151:13: error: variable 'npeers' set but not used [-Werror,-Wunused-but-set-variable]
 1151 |   size_t i, npeers = 0, ntickets = 0;
      |             ^
lib/vtls/vtls_scache.c:1151:25: error: variable 'ntickets' set but not used [-Werror,-Wunused-but-set-variable]
 1151 |   size_t i, npeers = 0, ntickets = 0;
      |                         ^