build: drop CURLDEBUG exceptions try 3
Failures:
https://github.com/curl/curl/actions/runs/13885099953/job/38848751169?pr=16738
prev (same):
https://github.com/curl/curl/actions/runs/13884173207/job/38846664216?pr=16738

```
lib\CMakeFiles\curlu.dir\Unity\unity_0_c.c.obj.d -o lib/CMakeFiles/curlu.dir/Unity/unity_0_c.c.obj -c D:/a/curl/curl/bld/lib/CMakeFiles/curlu.dir/Unity/unity_0_c.c
In file included from D:/a/curl/curl/lib/altsvc.c:49,
                 from D:/a/curl/curl/bld/lib/CMakeFiles/curlu.dir/Unity/unity_0_c.c:4:
D:/a/curl/curl/lib/getenv.c: In function 'GetEnv':
D:/a/curl/curl/lib/memdebug.h:140:19: error: 'curl_dbg_free' called on pointer 'mem' with nonzero offset 8 [-Werror=free-nonheap-object]
  140 | #define free(ptr) curl_dbg_free(ptr, __LINE__, __FILE__)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/getenv.c:61:7: note: in expansion of macro 'free'
   61 |       free(buf);
      |       ^~~~
In file included from D:/a/curl/curl/bld/lib/CMakeFiles/curlu.dir/Unity/unity_0_c.c:259:
In function 'curl_dbg_realloc',
    inlined from 'GetEnv' at D:/a/curl/curl/lib/getenv.c:48:11:
D:/a/curl/curl/lib/memdebug.c:265:9: note: returned from 'void *(void *, size_t)' {aka 'void *(void *, long long unsigned int)'}
  265 |   mem = (Curl_crealloc)(mem, size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'altsvc_free',
    inlined from 'altsvc_createid' at D:/a/curl/curl/lib/altsvc.c:130:3:
D:/a/curl/curl/lib/memdebug.h:140:19: error: 'curl_dbg_free' called on pointer returned from a mismatched allocation function [-Werror=mismatched-dealloc]
  140 | #define free(ptr) curl_dbg_free(ptr, __LINE__, __FILE__)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/altsvc.c:78:3: note: in expansion of macro 'free'
   78 |   free(as);
      |   ^~~~
D:/a/curl/curl/lib/altsvc.c: In function 'altsvc_createid':
D:/a/curl/curl/lib/memdebug.h:136:29: note: returned from 'curl_dbg_calloc.constprop'
  136 | #define calloc(nbelem,size) curl_dbg_calloc(nbelem, size, __LINE__, __FILE__)
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/curl/curl/lib/altsvc.c:90:23: note: in expansion of macro 'calloc'
   90 |   struct altsvc *as = calloc(1, sizeof(struct altsvc));
      |                       ^~~~~~
In function 'entry_free',
    inlined from 'Curl_dynhds_add' at D:/a/curl/curl/lib/dynhds.c:207:5:
D:/a/curl/curl/lib/memdebug.h:140:19: error: 'curl_dbg_free' called on pointer returned from a mismatched allocation function [-Werror=mismatched-dealloc]
  140 | #define free(ptr) curl_dbg_free(ptr, __LINE__, __FILE__)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
```

drop now unused MEMDEBUG_NODEFINES

memdebug.c: drop remaining MEMDEBUG_NODEFINES