build: silence DJGPP warnings due to unsigned `time_t` on MSDOS fixup
Trying to fix this in non-MSDOS envs:
```
../../lib/getinfo.c:241:33: error: result of comparison 'time_t' (aka 'long') < -9223372036854775808 is always false [-Werror,-Wtautological-type-limit-compare]
    else if(data->info.filetime < (time_t)LONG_MIN)
            ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~
```