try boringssl
neverbleed relies on features removed from LibreSSL ~3.9.x+

/home/runner/h2o-11b0cfa2771e3ccad4a852e72473e4e278ab1de7/deps/neverbleed/neverbleed.c:2237:86: error: implicit declaration of function ‘ENGINE_set_RSA’; did you mean ‘ENGINE_get_id’? [-Werror=implicit-function-declaration]
 2237 |             !ENGINE_set_name(nb->engine, "privilege separation software engine") || !ENGINE_set_RSA(nb->engine, rsa_method)
      |                                                                                      ^~~~~~~~~~~~~~
      |                                                                                      ENGINE_get_id
https://github.com/curl/curl/actions/runs/26568941711/job/78270796618