schannel: fix uninitialized result value
Initialize it to CURLE_OK to avoid reading a garbage value in cases.
A CURLE_OK is already used one level deeper than necessary in the
code, therefore thinking this is correct here. Checkme.

Follow-up to 7f4c358541fdadcf29ba20bcdff71c5554e5f69c #3197

https://github.com/curl/curl/actions/runs/13969308325/job/39106970359?pr=16764#step:8:511
```
/home/runner/work/curl/curl/lib/vtls/schannel.c:1635:14: error: Assigned value is garbage or undefined [clang-analyzer-core.uninitialized.Assign,-warnings-as-errors]
 1635 |       result = args.result;
      |              ^ ~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1542:3: note: Loop condition is false.  Exiting loop
 1542 |   DEBUGASSERT(ssl_connect_3 == connssl->connecting_state);
      |   ^
/home/runner/work/curl/curl/lib/curl_setup_once.h:301:24: note: expanded from macro 'DEBUGASSERT'
  301 | #define DEBUGASSERT(x) do { } while(0)
      |                        ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1543:3: note: Loop condition is false.  Exiting loop
 1543 |   DEBUGASSERT(backend);
      |   ^
/home/runner/work/curl/curl/lib/curl_setup_once.h:301:24: note: expanded from macro 'DEBUGASSERT'
  301 | #define DEBUGASSERT(x) do { } while(0)
      |                        ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1545:3: note: Loop condition is false.  Exiting loop
 1545 |   DEBUGF(infof(data,
      |   ^
/home/runner/work/curl/curl/lib/curl_setup_once.h:289:19: note: expanded from macro 'DEBUGF'
  289 | #define DEBUGF(x) do { } while(0)
      |                   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1549:6: note: Assuming field 'cred' is non-null
 1549 |   if(!backend->cred)
      |      ^~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1549:3: note: Taking false branch
 1549 |   if(!backend->cred)
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1553:6: note: Assuming field 'ret_flags' is equal to field 'req_flags'
 1553 |   if(backend->ret_flags != backend->req_flags) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1553:3: note: Taking false branch
 1553 |   if(backend->ret_flags != backend->req_flags) {
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1568:6: note: Assuming field 'use_alpn' is false
 1568 |   if(backend->use_alpn) {
      |      ^~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1568:3: note: Taking false branch
 1568 |   if(backend->use_alpn) {
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1603:6: note: Assuming field 'cache_session' is 0
 1603 |   if(ssl_config->primary.cache_session) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1603:3: note: Taking false branch
 1603 |   if(ssl_config->primary.cache_session) {
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1614:6: note: Assuming field 'certinfo' is not equal to 0
 1614 |   if(data->set.ssl.certinfo) {
      |      ^~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1614:3: note: Taking true branch
 1614 |   if(data->set.ssl.certinfo) {
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1621:9: note: Assuming 'sspi_status' is equal to SEC_E_OK
 1621 |     if((sspi_status != SEC_E_OK) || !ccert_context) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1621:8: note: Left side of '||' is false
 1621 |     if((sspi_status != SEC_E_OK) || !ccert_context) {
      |        ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1621:37: note: Assuming 'ccert_context' is non-null
 1621 |     if((sspi_status != SEC_E_OK) || !ccert_context) {
      |                                     ^~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1621:5: note: Taking false branch
 1621 |     if((sspi_status != SEC_E_OK) || !ccert_context) {
      |     ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1629:8: note: Assuming 'result' is 0
 1629 |     if(!result) {
      |        ^~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1629:5: note: Taking true branch
 1629 |     if(!result) {
      |     ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1634:7: note: Calling 'traverse_cert_store'
 1634 |       traverse_cert_store(ccert_context, add_cert_to_certinfo, &args);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1452:9: note: 'should_continue' is true
 1452 |   while(should_continue &&
      |         ^~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1452:9: note: Left side of '&&' is true
/home/runner/work/curl/curl/lib/vtls/schannel.c:1453:9: note: Assuming the condition is false
 1453 |         (current_context = CertEnumCertificatesInStore(
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1454 |           context->hCertStore,
      |           ~~~~~~~~~~~~~~~~~~~~
 1455 |           current_context)) != NULL) {
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1452:3: note: Loop condition is false. Execution continues on line 1467
 1452 |   while(should_continue &&
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1467:6: note: 'current_context' is null
 1467 |   if(current_context)
      |      ^~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1467:3: note: Taking false branch
 1467 |   if(current_context)
      |   ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1469:1: note: Returning without writing to 'arg->result'
 1469 | }
      | ^
/home/runner/work/curl/curl/lib/vtls/schannel.c:1634:7: note: Returning from 'traverse_cert_store'
 1634 |       traverse_cert_store(ccert_context, add_cert_to_certinfo, &args);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/curl/curl/lib/vtls/schannel.c:1635:14: note: Assigned value is garbage or undefined
 1635 |       result = args.result;
      |              ^ ~~~~~~~~~~~
```