ci switch to linux 1
It's _much_ faster and the binary cannot be run either way.

Forgot that Windows had long time lost the ability to run MS-DOS apps:
```
./bld/src/curl.exe
D:\a\_temp\64084e05-93ec-4615-9ce5-f859e0062200: line 2: bld/src/curl.exe: cannot execute binary file: Exec format error
Error: Process completed with exit code 126.
```
https://github.com/curl/curl/actions/runs/11879880480/job/33102346760#step:10:9