GHA/windows: add wince jobs try 1
add curl info step

GHA: fixup cm to link statically (shared is missing the implib)

GHA: fix curl info

GHA: skip building tests

```
In file included from /Users/runner/work/curl/curl/bld/tests/unit/unit_bundle.c:1994,
                 from /Users/runner/work/curl/curl/bld/tests/unit/CMakeFiles/units.dir/Unity/unity_0_c.c:4:
/Users/runner/work/curl/curl/tests/unit/unit1398.c:27: error: expected [error|warning|ignored] after '#pragma GCC diagnostic'
/Users/runner/work/curl/curl/tests/unit/unit1398.c:190: error: expected [error|warning|ignored] after '#pragma GCC diagnostic'
In file included from /Users/runner/work/curl/curl/bld/tests/unit/unit_bundle.c:4920,
                 from /Users/runner/work/curl/curl/bld/tests/unit/CMakeFiles/units.dir/Unity/unity_0_c.c:4:
/Users/runner/work/curl/curl/tests/unit/unit1652.c: In function 'test_unit1652':
/Users/runner/work/curl/curl/tests/unit/unit1652.c:96: error: #pragma GCC diagnostic not allowed inside functions
/Users/runner/work/curl/curl/tests/unit/unit1652.c:97: error: #pragma GCC diagnostic not allowed inside functions
/Users/runner/work/curl/curl/tests/unit/unit1652.c:98: error: #pragma GCC diagnostic not allowed inside functions
/Users/runner/work/curl/curl/tests/unit/unit1652.c:150: error: #pragma GCC diagnostic not allowed inside functions
In file included from /Users/runner/work/curl/curl/tests/unit/unit2600.c:44,
                 from /Users/runner/work/curl/curl/bld/tests/unit/unit_bundle.c:6117,
                 from /Users/runner/work/curl/curl/bld/tests/unit/CMakeFiles/units.dir/Unity/unity_0_c.c:4:
/Users/runner/opt/mingw32ce/bin/../lib/gcc/arm-mingw32ce/4.4.0/../../../../arm-mingw32ce/include/signal.h:12:26: error: no include path in which to search for signal.h
In file included from /Users/runner/work/curl/curl/bld/tests/unit/unit_bundle.c:6782,
                 from /Users/runner/work/curl/curl/bld/tests/unit/CMakeFiles/units.dir/Unity/unity_0_c.c:4:
/Users/runner/work/curl/curl/tests/unit/unit3200.c: At top level:
/Users/runner/work/curl/curl/tests/unit/unit3200.c:53: error: expected [error|warning|ignored] after '#pragma GCC diagnostic'
/Users/runner/work/curl/curl/tests/unit/unit3200.c:179: error: expected [error|warning|ignored] after '#pragma GCC diagnostic'
```
https://github.com/curl/curl/actions/runs/12736021108/job/35495445165#step:11:21

GHA/windows: disable DLL to make examples build

GHA/windows: move around mingw32ce jobs