lib677: rename file-wide static to avoid clash
```
D:/a/curl/curl/lib/warnless.c: In function 'curlx_read':
D:/a/curl/curl/lib/warnless.c:372:34: error: declaration of 'buf' shadows a global declaration [-Werror=shadow]
  372 | ssize_t curlx_read(int fd, void *buf, size_t count)
      |                            ~~~~~~^~~
In file included from D:/a/curl/curl/bld/tests/libtest/CMakeFiles/lib677.dir/Unity/unity_0_c.c:4:
D:/a/curl/curl/tests/libtest/lib677.c:31:13: note: shadowed declaration is here
   31 | static char buf[1024];
      |             ^~~
D:/a/curl/curl/lib/warnless.c: In function 'curlx_write':
D:/a/curl/curl/lib/warnless.c:377:41: error: declaration of 'buf' shadows a global declaration [-Werror=shadow]
  377 | ssize_t curlx_write(int fd, const void *buf, size_t count)
      |                             ~~~~~~~~~~~~^~~
D:/a/curl/curl/tests/libtest/lib677.c:31:13: note: shadowed declaration is here
   31 | static char buf[1024];
      |             ^~~
```
Ref: https://github.com/curl/curl/actions/runs/10682565270/job/29608750021?pr=14765