fix #if directive for non-Apple-gcc compilers
Linux gcc:
```
curl_setup.h:66:18: error: missing binary operator before token "("
   66 |    !__has_feature(attribute_availability))
      |                  ^
```
https://github.com/curl/curl/actions/runs/11729267034/job/32674506717?pr=15508#step:35:36

msvc:
```
lib\curl_setup.h(66,18): error C1012: unmatched parenthesis: missing ')'
```
https://github.com/curl/curl/actions/runs/11729267029/job/32674516200?pr=15508#step:9:20

clang compilers seem to be fine without this in all tested CI envs.