try clang-19
instead of the default 18.1.3

chasing this:
```
error: integer literal has suffix 'l', which is not uppercase [readability-uppercase-literal-suffix,-warnings-as-errors]
```
https://github.com/curl/curl/actions/runs/22194911487/job/64192567983?pr=20631#step:10:285