disable OpenLDAP for openssl cmake builds
autotools did not have openldap enabled, because it doesn't auto-detect it.
cmake does, and it causes pulling system libsasl2.so, which requires
non-deperecated openssl 3 function, and since its missing, linking curl fails:

/usr/bin/ld: /lib/x86_64-linux-gnu/libsasl2.so.2: undefined reference to `MD5_Final@OPENSSL_3.0.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libsasl2.so.2: undefined reference to `MD5_Update@OPENSSL_3.0.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libsasl2.so.2: undefined reference to `MD5_Init@OPENSSL_3.0.0'