asyn-ares.c silence unused macros (may be overkill)
```
/Users/runner/work/curl/curl/lib/asyn-ares.c:72:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
   72 | #define HAVE_CARES_IPV6 1
      |         ^
/Users/runner/work/curl/curl/lib/asyn-ares.c:111:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  111 | #define HAPPY_EYEBALLS_DNS_TIMEOUT 5000
      |         ^
2 warnings generated.
```
https://github.com/curl/curl/actions/runs/17561982725/job/49880306836?pr=18477#step:11:32