Revert "test: delete the complete workaround, see CI"
This reverts commit c03ee71e4bf0a8c4c6770966e48b0544168a20d1.

In reproduces in CI:

Step 1, here is the cmake lib order + binutils ld issue reproduced:
https://github.com/curl/curl/actions/runs/21332437230/job/61399234023?pr=20427
https://github.com/curl/curl/actions/runs/21332437230/job/61399234033?pr=20427
(hitting zlib and ws2_32. openssl is fine in these tests)

Linux gcc glibc (amd64, arm64):
```
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: /home/runner/work/curl/curl/libssh2/_a64-linux-gnu-libressl/usr/lib/libssh2.a(unity_0_c.c.o): in function `comp_method_zlib_dtor':
(.text.comp_method_zlib_dtor+0x94): undefined reference to `deflateEnd'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: /home/runner/work/curl/curl/libssh2/_a64-linux-gnu-libressl/usr/lib/libssh2.a(unity_0_c.c.o): in function `comp_method_zlib_comp':
(.text.comp_method_zlib_comp+0x54): undefined reference to `deflate'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: /home/runner/work/curl/curl/libssh2/_a64-linux-gnu-libressl/usr/lib/libssh2.a(unity_0_c.c.o): in function `comp_method_zlib_init':
(.text.comp_method_zlib_init+0x90): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
```

Windows gcc zlib-classic (x64):
```
/usr/bin/x86_64-w64-mingw32-ld: /home/runner/work/curl/curl/libssh2/_x64-win-ucrt-libressl/usr/lib/libssh2.a(unity_0_c.c.obj):(.text$comp_method_zlib_dtor+0x49): undefined reference to `deflateEnd'
/usr/bin/x86_64-w64-mingw32-ld: /home/runner/work/curl/curl/libssh2/_x64-win-ucrt-libressl/usr/lib/libssh2.a(unity_0_c.c.obj):(.text$comp_method_zlib_comp+0x3c): undefined reference to `deflate'
/usr/bin/x86_64-w64-mingw32-ld: /home/runner/work/curl/curl/libssh2/_x64-win-ucrt-libressl/usr/lib/libssh2.a(unity_0_c.c.obj):(.text$comp_method_zlib_init+0xc6): undefined reference to `deflateInit_'
/usr/bin/x86_64-w64-mingw32-ld: /home/runner/work/curl/curl/libpsl/_x64-win-ucrt/usr/lib/libpsl.a(psl.o):(.text$psl_is_cookie_domain_acceptable+0xff): undefined reference to `__imp_WSAStringToAddressW'
collect2: error: ld returned 1 exit status
```
(this particular fallout is avoided in libpsl, but not released yet: https:||github.com/rockdaboot/libpsl/pull/228 https:||github.com/rockdaboot/libpsl/commit/356c07343f842bb23cbbec6087af07c52521e16a. But, even with this, it can happen in misc other cases.)