disable due to
```
/home/runner/work/curl/curl/lib/cf-socket.c:1597:52: error: operator has equivalent nested operands [misc-redundant-expression,-warnings-as-errors]
 1597 |   pfd[0].events = POLLRDNORM | POLLIN | POLLRDBAND | POLLPRI;
      |                                                    ^
631 warnings generated.
```
https://github.com/curl/curl/actions/runs/22603450627/job/65490313441?pr=20794