Revert "unit1615.c try dropping silencer hack"
This reverts commit d3096bdd916fa6ad8822bcfe492c459b8665a58f.

```
../../../tests/unit/unit1615.c: In function 'test_unit1615':
../../../tests/libtest/unitcheck.h:51:8: error: the address of 'output_buf' will always evaluate as 'true' [-Werror=address]
   51 |     if((dynamic) && memcmp(dynamic, check, len)) {                          \
      |        ^
../../../tests/unit/unit1615.c:114:3: note: in expansion of macro 'verify_memory'
  114 |   verify_memory(output_buf, precomp_hash1, CURL_SHA512_256_DIGEST_LENGTH);
      |   ^~~~~~~~~~~~~
```
https://github.com/curl/curl/actions/runs/26764765630/job/78887931381?pr=21830#step:47:79