vtls.c fix unused const vars
/lib/vtls/vtls.c:141:31: error: unused variable 'ALPN_SPEC_H2' [clang-diagnostic-unused-const-variable]
  141 | static const struct alpn_spec ALPN_SPEC_H2 = {
      |                               ^~~~~~~~~~~~
lib/vtls/vtls.c:144:31: error: unused variable 'ALPN_SPEC_H2_H11' [clang-diagnostic-unused-const-variable]
  144 | static const struct alpn_spec ALPN_SPEC_H2_H11 = {
      |                               ^~~~~~~~~~~~~~~~
lib/vtls/vtls.c:147:31: error: unused variable 'ALPN_SPEC_H11_H2' [clang-diagnostic-unused-const-variable]
  147 | static const struct alpn_spec ALPN_SPEC_H11_H2 = {
      |                               ^~~~~~~~~~~~~~~~