try ram disk 1
try ram disk 2

try ram disk 3

try ram disk 4

fixup for arm64

Revert "GHA/windows: switch to windows-2025 runners?"

This reverts commit 8de70fdd24a7161e50051cae92ef70badff94863.

try ram disk 5

fixups

Reapply "GHA/windows: switch to windows-2025 runners?"

This reverts commit 954865a98b8c64bbf25bd5062f0cc38097552274.

show size

more ram disk 1

move ram disk 2

move ram disk 3

move ram disk 4 fix configure

move ram disk 5

move ram disk 6

move ssh server to R:

try on windows-2022

Revert "move ssh server to R:"

This reverts commit e61529c08f158ede7f19aa905d00e8c019d6ad2c.

Probbaly pointless. It also broke ARM runners where there is no R:

cleanup

try FAT32

try FAT32 2

try FAT32 3

try FAT32 4

try FAT32 5 drop

try on windows-2022 fixup

cleanup

try moving source to RAM disk too

try with rest of jobs

try with rest of jobs 2

apply change to new lines after rebase

shorten

try manual install

try manual install 2

fix install script to skip hangers on ARM64

Hangs on the ARM64 runner:
```
ImDisk Virtual Disk Driver setup
Number of existing ImDisk virtual disks: 0
The service name is invalid.
More help is available by typing NET HELPMSG 2185.
The service name is invalid.
More help is available by typing NET HELPMSG 2185.
The service name is invalid.
More help is available by typing NET HELPMSG 2185.
ERROR: The process "imdsksvc.exe" not found.
```
https://github.com/curl/curl/actions/runs/16727089946/job/47345925663?pr=18039#step:3:26

timeout

manual install

manual install 2

manual install 3

manual install 4

manual install 5

manual install 6

manual install 7

manual install 8

manual install 9

manual install 10

wramdisk.sh detect platform, verify hash

try something 1

cleanup

try something 2

try something 3

try something 4

try something 5

tweak sizes

cleanup

tweak

fixup

cleanup

cleanup

cleanup

cleanup

cache

cache 2

cache 2 fixup

cache 3

cleanup

limit ram disk size for cygwin

42M	.
877M	/cygdrive/r/cygwin
162M	/cygdrive/r/cygwin-packages
19M	/cygdrive/r/bld

31M	.
913M	/cygdrive/r/cygwin
172M	/cygdrive/r/cygwin-packages
29M	/cygdrive/r/bld

cleanups

fixup

fixup to go back to 2022