sectransp: fix clang `-Wpointer-bool-conversion`, stop silencing them
Verified with clang 14, llvm 15, llvm 18 and gcc 14 that the generated
objects are bit by bit identical before and after this patch.

cmake clang:
```
curl/lib/vtls/sectransp.c:1103:6: error: address of function 'SSLCreateContext' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
  if(SSLCreateContext) {  /* use the newer API if available */
  ~~ ^~~~~~~~~~~~~~~~
curl/lib/vtls/sectransp.c:1103:6: note: prefix with the address-of operator to silence this warning
  if(SSLCreateContext) {  /* use the newer API if available */
     ^
     &
```
Ref: https://github.com/curl/curl/actions/runs/9819538439/job/27113201384#step:8:382

cmake llvm:
```
curl/lib/vtls/sectransp.c:2663:8: error: address of function 'SSLCreateContext' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
    if(SSLCreateContext)
    ~~ ^~~~~~~~~~~~~~~~
curl/lib/vtls/sectransp.c:2663:8: note: prefix with the address-of operator to silence this warning
    if(SSLCreateContext)
       ^
       &
```
Ref: https://github.com/curl/curl/actions/runs/9819538439/job/27113200291#step:8:417

missing from autotools clang and llvm. why? [BECAUSE -Wno-pointer-bool-conversion was set for darwin builds in autotools]

This is a -Waddress warning with GCC:

cmake gcc-11:
```
curl/lib/vtls/sectransp.c: In function 'sectransp_close':
curl/lib/vtls/sectransp.c:2663:8: error: the address of 'SSLCreateContext' will always evaluate as 'true' [-Werror=address]
 2663 |     if(SSLCreateContext)
      |        ^~~~~~~~~~~~~~~~
```
Ref: https://github.com/curl/curl/actions/runs/9819538439/job/27113198568#step:8:386

autotools gcc-11:
```
../../lib/vtls/sectransp.c:498:6: error: the address of 'SecItemCopyMatching' will always evaluate as 'true' [-Werror=address]
  498 |   if(&SecItemCopyMatching && kSecClassIdentity) {
      |      ^
../../lib/vtls/sectransp.c: In function 'set_ssl_version_min_max':
../../lib/vtls/sectransp.c:794:6: error: the address of 'SSLSetProtocolVersionMax' will always evaluate as 'true' [-Werror=address]
  794 |   if(&SSLSetProtocolVersionMax) {
      |      ^
../../lib/vtls/sectransp.c: In function 'sectransp_connect_step1':
../../lib/vtls/sectransp.c:1102:6: error: the address of 'SSLCreateContext' will always evaluate as 'true' [-Werror=address]
 1102 |   if(&SSLCreateContext) {  /* use the newer API if available */
      |      ^
../../lib/vtls/sectransp.c:1136:6: error: the address of 'SSLSetProtocolVersionMax' will always evaluate as 'true' [-Werror=address]
```
Ref: https://github.com/curl/curl/actions/runs/9819993309/job/27114114774#step:8:500

Cherry-picked from #14097
Closes #xxxxx