Revert "cf-socket.c: add missing intermediate const"
This reverts commit 75cd8e0298d8a658d9551203a6c9d4320e9da146.

```
In file included from libcurl_unity.c:13:
../../lib/cf-socket.c: In function 'bindlocal':
../../lib/cf-socket.c:734:32: error: passing argument 1 of 'Curl_str_number' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  734 |             if(Curl_str_number((const char * const *)&scope_ptr, &scope_id,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../lib/altsvc.c:43:
../../lib/strparse.h:79:34: note: expected 'const char **' but argument is of type 'const char * const*'
   79 | int Curl_str_number(const char **linep, curl_off_t *nump, curl_off_t max);
      |                     ~~~~~~~~~~~~~^~~~~
In file included from libcurl_unity.c:13:
../../lib/cf-socket.c: In function 'bindlocal':
../../lib/cf-socket.c:734:32: error: passing argument 1 of 'Curl_str_number' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  734 |             if(Curl_str_number((const char * const *)&scope_ptr, &scope_id,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../lib/altsvc.c:43:
../../lib/strparse.h:79:34: note: expected 'const char **' but argument is of type 'const char * const*'
   79 | int Curl_str_number(const char **linep, curl_off_t *nump, curl_off_t max);
      |                     ~~~~~~~~~~~~~^~~~~
```