Revert "test fil-c on arm64"
This reverts commit e559bbbc5922b6aab0d7befce1ec2435fc8d76df.

Tested Fil-C on ARM64 successfully, with one pytest fallout:
```
FAILED ../../tests/http/test_20_websockets.py::TestWebsockets::test_20_11_crazy_pings - AssertionError: bad memory increase
assert (51.703125 * 1.2) > 63.703125
================= 1 failed, 527 passed, 316 skipped in 31.22s ==================
```
Ref: https://github.com/curl/curl/actions/runs/37004816848/job/110830492543