Revert "mk-unity maybe"
This reverts commit 9255fd18536ec3d18a5e70de749b1c5475807fc7.

No:
https://github.com/curl/curl/actions/runs/30256644523/job/89946690446?pr=22406

```
Error while processing /Users/runner/work/curl/curl/tests/server/tftpd.c.
/Users/runner/work/curl/curl/tests/server/first.c:41:16: error: use of undeclared identifier 's_entries' [clang-diagnostic-error]
Suppressed 3467 warnings (3459 in non-user code, 8 with check filters).
   41 |   for(tmp = 0; s_entries[tmp].ptr; ++tmp) {
      |                ^~~~~~~~~
/Users/runner/work/curl/curl/tests/server/first.c:42:28: error: use of undeclared identifier 's_entries' [clang-diagnostic-error]
   42 |     if(!strcmp(entry_name, s_entries[tmp].name)) {
      |                            ^~~~~~~~~
/Users/runner/work/curl/curl/tests/server/first.c:43:20: error: use of undeclared identifier 's_entries' [clang-diagnostic-error]
```