tool1621: drop stray libcurl internal headers
Fixing this error with PR 16973 applied:
```
[4/4] Processing file /Users/runner/work/curl/curl/tests/tunit/tool1621.c.
1 error generated.
Error while processing /Users/runner/work/curl/curl/tests/tunit/tool1621.c.
/Users/runner/work/curl/curl/lib/psl.h:28:10: error: 'libpsl.h' file not found [clang-diagnostic-error]
   28 | #include <libpsl.h>
      |          ^~~~~~~~~~
FAILED: [code=1] tests/tunit/CMakeFiles/tunits-clang-tidy /Users/runner/work/curl/curl/bld/tests/tunit/CMakeFiles/tunits-clang-tidy
```
https://github.com/curl/curl/actions/runs/16055441393/job/45308545907?pr=16973#step:14:539

The applied PR remove dependency header directories from the global
scope, which means they are no longer passed to the tunits build.
Correctly so, but this also revealed that tool1621 was in fact depending
on dependency headers via internal libcurl header that were included.
These headers weren't used, so just drop them as a fix.