unit1300.c: fix unused value
```
tests/unit/unit1300.c:63:10: error: Value stored to 'llist_size' during its initialization is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
   63 |   size_t llist_size = Curl_llist_count(&llist);
      |          ^~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~
tests/unit/unit1300.c:63:10: note: Value stored to 'llist_size' during its initialization is never read
   63 |   size_t llist_size = Curl_llist_count(&llist);
      |          ^~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~
```

Ref ba235ab269080dc66e35835c829f7ac4290dbc1d