lib: fix missing `getpwuid()` declaration with AmigaOS
`curl_setup.h` sets `__NO_NET_API` for AmigaOS as a workaround.
This workaround has the side-effect of disabling the prototype of
`getpwuid()` in `pwd.h`. `src/tool_findfile.c` already used a workaround
for this issue. Apply that workaround also to `lib/netrc.c`.

Also:
- update workaround to define `__NO_NET_API` again after including
  `pwd.h`. To ensure the workaround remains set in unity builds.
- update comment and sync formatting in the two files.

Fixes:
```
../../lib/netrc.c: In function 'Curl_parsenetrc':
../../lib/netrc.c:367:12: error: implicit declaration of function 'getpwuid' [-Werror=implicit-function-declaration]
       pw = getpwuid(geteuid());
            ^~~~~~~~
../../lib/netrc.c:367:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       pw = getpwuid(geteuid());
          ^
```