cmake: fix build with the FASTBuild generator
To silence many of these warnings:
```
11>/tmp/_fbuild.tmp/0x0752c383/core_2/70816E19/krb5_sspi.c:1:5: error: this style of line directive is a GNU extension [-Werror,-Wgnu-line-marker]
    1 | # 1 "<built-in>"
      |     ^
/path/to/curl/lib/vauth/krb5_sspi.c:29:6: error: this style of line directive is a GNU extension [-Werror,-Wgnu-line-marker]
   29 | # 26 "/path/to/curl/lib/vauth/krb5_sspi.c"
      |      ^
```

FASTBuild is slightly faster than Ninja in basic (single-machine, build
from scratch) cases. It doesn't support unity builds. Maybe it can bring
slightly better performance to non-unity cmake jobs, in jobs having
an 'install prereq' phase, and installing the fastbuild package is
faster than this gain. It overall seems marginal if any in curl CI.
At least for now. But it doesn't hurt if it works, and may be useful for
some.

Requires CMake 4.2+.

Refs:
https://www.kitware.com/cmake-fastbuild-distributed-cached-and-fast/
https://cmake.org/cmake/help/latest/generator/FASTBuild.html