linux: move libssh2 to a new, migrated job
In the previous one, the build failed due to stdc89, with this:
```
unit2604.c: In function ‘test’:
unit2604.c:56:5: error: string length ‘542’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
   56 |     { SA540 " c", SA540, "c", "/", CURLE_OK},
      |     ^
unit2604.c:56:5: error: string length ‘540’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
unit2604.c:57:5: error: string length ‘545’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
   57 |     { "\" " SA540 "\" c", " " SA540, "c", "/", CURLE_OK},
      |     ^
unit2604.c:57:5: error: string length ‘541’ is greater than the length ‘509’ ISO C90 compilers are required to support [-Woverlength-strings]
make[1]: *** [Makefile:1224: unit2604.o] Error 1
```
Ref: https://github.com/curl/curl/actions/runs/10840223352/job/30082133462?pr=14859

It's also nt great to link in libssh2 with the custom built openssl3,
as it will lead to two openssl libs linked to curl.