lib/vtls/vtls_{scache,spack}: replace `uchar*` with `void*` to avoid 'increases required alignment from 1 to 2' `-Wcast-align`
clang:
```
../../lib/vtls/bearssl.c:619:17: error: cast from 'const unsigned char *' to 'const br_ssl_session_parameters *' increases required alignment from 1 to 2 [-Werror,-Wcast-align]
  619 |       session = (const br_ssl_session_parameters *)sc_session->sdata;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcurl_unity.c:147:
../../lib/vtls/bearssl.c:619:17: error: cast from 'const unsigned char *' to 'const br_ssl_session_parameters *' increases required alignment from 1 to 2 [-Werror,-Wcast-align]
  619 |       session = (const br_ssl_session_parameters *)sc_session->sdata;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://github.com/curl/curl/actions/runs/13619899583/job/38067821052?pr=16142#step:35:67