add hack for libuv + memdebug + unity mode
We need to undo a previous override to avoid applying it to
system headers, and messing them up:
```
In file included from ~/curl/_build-cmake-libressl/src/CMakeFiles/curl.dir/Unity/unity_0_c.c:88:
In file included from ~/curl/src/tool_operate.c:54:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv.h:71:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv/unix.h:34:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:269:7: error: expected parameter declarator
void            freeaddrinfo(struct addrinfo *);
                ^
~/curl/lib/memdebug.h:167:31: note: expanded from macro 'freeaddrinfo'
  curl_dbg_freeaddrinfo(data, __LINE__, __FILE__)
                              ^
<scratch space>:102:1: note: expanded from here
269
^
In file included from ~/curl/_build-cmake-libressl/src/CMakeFiles/curl.dir/Unity/unity_0_c.c:88:
In file included from ~/curl/src/tool_operate.c:54:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv.h:71:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv/unix.h:34:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:269:7: error: expected ')'
~/curl/lib/memdebug.h:167:31: note: expanded from macro 'freeaddrinfo'
  curl_dbg_freeaddrinfo(data, __LINE__, __FILE__)
                              ^
<scratch space>:102:1: note: expanded from here
269
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:269:7: note: to match this '('
~/curl/lib/memdebug.h:167:24: note: expanded from macro 'freeaddrinfo'
  curl_dbg_freeaddrinfo(data, __LINE__, __FILE__)
                       ^
In file included from ~/curl/_build-cmake-libressl/src/CMakeFiles/curl.dir/Unity/unity_0_c.c:88:
In file included from ~/curl/src/tool_operate.c:54:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv.h:71:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv/unix.h:34:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:271:6: error: expected parameter declarator
int             getaddrinfo(const char * __restrict, const char * __restrict,
                ^
~/curl/lib/memdebug.h:160:47: note: expanded from macro 'getaddrinfo'
  curl_dbg_getaddrinfo(host, serv, hint, res, __LINE__, __FILE__)
                                              ^
<scratch space>:104:1: note: expanded from here
273
^
In file included from ~/curl/_build-cmake-libressl/src/CMakeFiles/curl.dir/Unity/unity_0_c.c:88:
In file included from ~/curl/src/tool_operate.c:54:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv.h:71:
In file included from /usr/local/Cellar/libuv/1.48.0/include/uv/unix.h:34:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:271:6: error: expected ')'
~/curl/lib/memdebug.h:160:47: note: expanded from macro 'getaddrinfo'
  curl_dbg_getaddrinfo(host, serv, hint, res, __LINE__, __FILE__)
                                              ^
<scratch space>:104:1: note: expanded from here
273
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/netdb.h:271:6: note: to match this '('
~/curl/lib/memdebug.h:160:23: note: expanded from macro 'getaddrinfo'
  curl_dbg_getaddrinfo(host, serv, hint, res, __LINE__, __FILE__)
                      ^
4 errors generated.
```