gtls.c fix unused var warning with nettle4
```
/Users/runner/work/curl/curl/lib/vtls/gtls.c:2267:39: error: unused parameter 'sha256len' [clang-diagnostic-unused-parameter,-warnings-as-errors]
 2267 |                                size_t sha256len)
      |                                       ^
```
Ref: https://github.com/curl/curl/actions/runs/25710321195/job/75488970143?pr=21557