unit2600: drop unused headers
```
error: no include path in which to search for signal.h
```
https://github.com/curl/curl/actions/runs/12739922622/job/35504362939#step:11:23

Unused since 3514a394f361616d2607b8f693b796e04a4189a8