GHA/linux: enable wolfssl multissl, wolfssh ech, kerberos for clang-tidy
use wolfssl-opensslextra, wolfssl-all can't coexist with OpenSSL

https://github.com/curl/curl/actions/runs/13954938367/job/39063594980?pr=16764#step:35:973

GHA/linux: fix to use clang instead of gcc for tidy job

Mixing them did not cause visible issues on Linux, but let's do the right
thing and not mix the two compiler within one build run anyway.

Fallout with clang:

https://github.com/curl/curl/actions/runs/13968536911/job/39104504198?pr=16764#step:31:348

```
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lpsl  -lwolfssl -lm -lssl -lcrypto -lssl -lcrypto  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lgssapi_krb5  -lzstd  -lbrotlidec  -lz
Error: Process completed with exit code 1.
```

```
configure:34772: checking run-time libs availability
configure:34828: sh ./run-compiler -o conftest -Qunused-arguments -Werror-implicit-function-declaration -O2 -pedantic -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wshadow -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wsign-compare -Wno-multichar -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wcast-align -Wno-system-headers -Wshorten-64-to-32 -Wunused -Waddress -Wattributes -Wbad-function-cast -Wconversion -Wdiv-by-zero -Wformat-security -Wempty-body -Wmissing-field-initializers -Wmissing-noreturn -Wold-style-definition -Wredundant-decls -Wtype-limits -Wunreachable-code -Wunused-parameter -Wignored-qualifiers -Wvla -Wno-sign-conversion -Wshift-sign-overflow -Wcast-qual -Wlanguage-extension-token -Wformat=2 -Wenum-conversion -Wsometimes-uninitialized -Wmissing-variable-declarations -Wheader-guard -Wunused-const-variable -Wpragmas -Wdouble-promotion -Wcomma -Wassign-enum -Wextra-semi-stmt -Wimplicit-fallthrough  -D_GNU_SOURCE    -isystem /usr/include/mit-krb5   -I/home/runner/wolfssl-opensslextra/include  -I/home/runner/wolfssh/include -Wl,-rpath,/home/runner/wolfssl-opensslextra/lib     -L/home/runner/wolfssl-opensslextra/lib  -L/home/runner/wolfssh/lib -lwolfssh -lwolfssl -lutil conftest.c -lpsl  -lwolfssl -lm -lssl -lcrypto -lssl -lcrypto  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lgssapi_krb5  -lzstd  -lbrotlidec  -lz   >&5
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_sign_msg'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_final'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_import_public'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_update'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_export_public'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_init'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_Ed25519PublicKeyDecode'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_free'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_sig_size'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_AesCtrEncrypt'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_Ed25519PrivateKeyDecode'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_SSH_KDF'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_import_private_key'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_init_ex'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

drop clang instead of gcc idea on linux

There is no wolfcrypto.a lib, no idea why this comes up with clang but not
with gcc. linker is the same: ld. (wolfssh/ssl are built with gcc, and they
are both .so)

due to:
https://github.com/curl/curl/actions/runs/13968536911/job/39104504198?pr=16764#step:31:348

```
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lpsl  -lwolfssl -lm -lssl -lcrypto -lssl -lcrypto  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lgssapi_krb5  -lzstd  -lbrotlidec  -lz
Error: Process completed with exit code 1.
```

```
configure:34772: checking run-time libs availability
configure:34828: sh ./run-compiler -o conftest -Qunused-arguments -Werror-implicit-function-declaration -O2 -pedantic -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wshadow -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wsign-compare -Wno-multichar -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wcast-align -Wno-system-headers -Wshorten-64-to-32 -Wunused -Waddress -Wattributes -Wbad-function-cast -Wconversion -Wdiv-by-zero -Wformat-security -Wempty-body -Wmissing-field-initializers -Wmissing-noreturn -Wold-style-definition -Wredundant-decls -Wtype-limits -Wunreachable-code -Wunused-parameter -Wignored-qualifiers -Wvla -Wno-sign-conversion -Wshift-sign-overflow -Wcast-qual -Wlanguage-extension-token -Wformat=2 -Wenum-conversion -Wsometimes-uninitialized -Wmissing-variable-declarations -Wheader-guard -Wunused-const-variable -Wpragmas -Wdouble-promotion -Wcomma -Wassign-enum -Wextra-semi-stmt -Wimplicit-fallthrough  -D_GNU_SOURCE    -isystem /usr/include/mit-krb5   -I/home/runner/wolfssl-opensslextra/include  -I/home/runner/wolfssh/include -Wl,-rpath,/home/runner/wolfssl-opensslextra/lib     -L/home/runner/wolfssl-opensslextra/lib  -L/home/runner/wolfssh/lib -lwolfssh -lwolfssl -lutil conftest.c -lpsl  -lwolfssl -lm -lssl -lcrypto -lssl -lcrypto  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lgssapi_krb5  -lzstd  -lbrotlidec  -lz   >&5
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_sign_msg'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_final'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_import_public'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_update'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_export_public'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_init'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_Ed25519PublicKeyDecode'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_free'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_sig_size'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_AesCtrEncrypt'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_Ed25519PrivateKeyDecode'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_SSH_KDF'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_import_private_key'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_init_ex'
/usr/bin/ld: /home/runner/wolfssh/lib/libwolfssh.so: undefined reference to `wc_ed25519_verify_msg_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

linux: sslexport