first.h #if 0 unused macros
```
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:73:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
   73 | #define test_multi_setopt(A, B, C)       \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:244:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  244 | #define res_multi_setopt(A, B, C) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:298:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  298 | #define res_multi_remove_handle(A, B) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:434:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  434 | #define res_multi_poll(A, B, C, D, E) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:464:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  464 | #define chk_multi_wakeup(A, Y, Z) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:471:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  471 | #define multi_wakeup(A) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:526:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  526 | #define res_test_timedout_custom(T) \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:572:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
  572 | #define NO_SUPPORT_BUILT_IN                     \
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:8981:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 8981 | #define T518_SAFETY_MARGIN 16
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:8983:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 8983 | #define NUM_OPEN   (FD_SETSIZE + 10)
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:8984:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 8984 | #define NUM_NEEDED (NUM_OPEN + T518_SAFETY_MARGIN)
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:8987:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 8987 | #define DEV_NULL "NUL"
      |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:10694:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 10694 | #define T537_SAFETY_MARGIN 11
       |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:10697:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 10697 | #define DEV_NULL "NUL"
       |         ^
/home/runner/work/curl/curl/bld/tests/libtest/libtests.c:30773:9: error: macro is not used [clang-diagnostic-unused-macros,-warnings-as-errors]
 30773 | #define print_err(name, exp)                                            \
       |         ^
```
https://github.com/curl/curl/actions/runs/25709680996/job/75487096092?pr=21554