use official libressl tarball instead of the repo
It evolved from building from master, then switched to a stable
tag and kept using the repo.
6f42e3b16968efded56238b4bce91242a0c29983 #5932

Repo method is fragile, currently broken:
```
Note: switching to '7a0f690de4dbb4bb7a7078b4fae3e1ec6e764390'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

pulling upstream openbsd source
Cloning into 'openbsd'...
fatal: ambiguous argument 'OPENBSD_7_6': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
This is tag v4.0.0, trying OpenBSD tag libressl-v4.0.0
error: pathspec 'libressl-v4.0.0' did not match any file(s) known to git
No matching OpenBSD tag found trying nearest commit
libcrypto version 55:0:0
libssl version 58:0:0
libtls version 31:0:0
LibreSSL version 4.0.0
copying libcrypto source
generating mips ASM source for elf
generating mips64 ASM source for elf
generating arm ASM source for elf
generating x86_64 ASM source for elf
Can't open perl script "/home/runner/work/curl/curl/libressl-git/openbsd/src/lib/libcrypto/sha/asm/sha512-x86_64.pl": No such file or directory
```
https://github.com/curl/curl/actions/runs/11964721579/job/33357524410#step:10:20