document and fix the "availability" gcc fallout
Summary: https://github.com/curl/curl/pull/14091#issuecomment-2222703468

Example fallouts:
https://github.com/curl/curl/actions/runs/9860040784/job/27225311116

This feature was patched into gcc 12.4.0 via an Apple compatibility pack
that is applied to mainline gcc by Homebrew:
https://github.com/iains/gcc-12-branch/commit/fd5530b7cb0012bf4faeddd45e13054a1dfa6783

What remains unexplained is why this error started happening after
upgrading gcc-12 from 12.3.0 to 12.4.0:

CI example with gcc 12.4.0 and macOS SDK 14.0 (Xcode 15.0.1):
```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:54,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCDynamicStoreCopySpec
ific.h:30,
                 from /Users/runner/work/curl/curl/lib/macos.c:33,
                 from /Users/runner/work/curl/curl/build/lib/CMakeFiles/libcurl_shared.dir/Unity/unity_0_c.c:244:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFUserNotification.h:126:1: error: attributes should be specified before the declarator in a function definition
  126 | CF_INLINE CFOptionFlags CFUserNotificationCheckBoxChecked(CFIndex i) API_AVAILABLE(macos(10.0)) API_UNAVAILABLE(ios, watchos, tvos) {return ((CFOptionFlags)(1UL << (8 + i)));}
      | ^~~~~~~~~
```
Ref: https://github.com/curl/curl/actions/runs/9787982387/job/27025351601?pr=14096#step:7:18

Oddly enough gcc 12.3.0 and macOS SDK 14.0 (Xcode 15.0.1) were
_compatible_:
https://github.com/curl/curl/actions/runs/9791701214/job/27036037162

Follow-up to db135f8d7207b20d531e7e2100a49f3e16bdcfab #14119
Fixes #13700
Closes #xxxxx

gcc + SecureTransport incompatibility

Caused by gcc 12 introducing the `availability` attribute:
  https://github.com/gcc-mirror/gcc/commit/8433baadec88e5f31fa141b6d78094e91256079d
SDK headers use it if available, but the feature is not fully compatible with clang.
Then the way the SDK places the attributes breaks the build with exotic errors. It
remains the case as of gcc 14. The errors are:
  error: attributes should be specified before the declarator in a function definition
  error: expected ',' or '}' before

It seems the attribute feature was introduced by gcc. Which llvm implemented, but
with difference (over time). gcc also has different behaviour in C++ and C. There is
now an open bug with gcc to adjust behaviour (though it's unclear to me if this would
cover the actual cases hit by Apple SDK and/or curl):

https://github.com/llvm/llvm-project/issues/81767
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108796
https://discourse.llvm.org/t/changing-attribute-ast-printing-location-for-gcc-compatibility/73215
https://reviews.llvm.org/D159362

It can be fixed by patching out `__has_attribute(availability)` check with `0` in
the SDK. The ones affecting curl are in `os/availability.h` and
`CoreFoundation/CFAvailability.h`. There a handful more in the SDK:

```
//--- a/<sdkroot>/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h
//+++ b/<sdkroot>/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h
@@ -93,7 +93,7 @@
 #define CF_DEPRECATED_IPHONE(_iosIntro, _iosDep) CF_DEPRECATED_IOS(_iosIntro, _iosDep)

 // Enum availability macros
-#if __has_feature(enumerator_attributes) && __has_attribute(availability)
+#if __has_feature(enumerator_attributes) && __has_attribute(availability) && 0
 #define CF_ENUM_AVAILABLE(_mac, _ios) CF_AVAILABLE(_mac, _ios)
 #define CF_ENUM_AVAILABLE_MAC(_mac) CF_AVAILABLE_MAC(_mac)
 #define CF_ENUM_AVAILABLE_IOS(_ios) CF_AVAILABLE_IOS(_ios)

//--- a/<sdkroot>/usr/include/os/availability.h
//+++ b/<sdkroot>/usr/include/os/availability.h
@@ -78,7 +78,7 @@

 #if defined(__has_feature) && defined(__has_attribute)
- #if __has_attribute(availability)
+ #if __has_attribute(availability) && 0

     /*
      * API Introductions
```

try TARGET fix 3

Also move TargetConditionals.h to the top of the headers,
also making sure that it's included for USE_ARES builds.
They also need this if using SecureTransport or other stuff
touching the Apple SDK.

Example fallout:
https://github.com/curl/curl/actions/runs/9893867519/job/27330136414

--------------------------------------- old:

try TARGET fix 1

Remaining fallouts after moving TargetConditionals.h to the top:
https://github.com/curl/curl/actions/runs/9893668164/job/27329383470

(without the manual TARGET_* macro hack)

try TARGET fix 2

Remaining fallouts after adding sys/types.h:
https://github.com/curl/curl/actions/runs/9893867519/job/27330136414

(still without the manual TARGET_* macro hack)